#!/usr/bin/env bash
# Generated by clarte - do not edit
# Runs tests and outputs a structured one-line summary.
# Usage: .clarte/scripts/check-tests.sh [extra-args...]
set -o pipefail

BASE_CMD="bun run test"
EXTRA_ARGS="$*"
CMD="$BASE_CMD${EXTRA_ARGS:+ $EXTRA_ARGS}"

TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT

eval "$CMD" 2>&1 | tee "$TMPFILE"
EXIT_CODE=${PIPESTATUS[0]}

# Strip ANSI escape codes for reliable parsing
CLEAN=$(mktemp)
trap 'rm -f "$TMPFILE" "$CLEAN"' EXIT
sed $'s/\x1b\\[[0-9;]*m//g' "$TMPFILE" > "$CLEAN"

PASS_COUNT="?"
FAIL_COUNT="?"
SKIP_INFO=""
FAIL_NAMES=""

# Vitest output: "Tests  42 passed | 2 failed | 1 skipped (45)"
LINE=$(grep -E 'Tests\s+[0-9]' "$CLEAN" | tail -1)
if [ -n "$LINE" ]; then
  PASS_COUNT=$(echo "$LINE" | sed -n 's/.*[^0-9]\([0-9][0-9]*\) passed.*/\1/p')
  FAIL_COUNT=$(echo "$LINE" | sed -n 's/.*[^0-9]\([0-9][0-9]*\) failed.*/\1/p')
  SKIPPED=$(echo "$LINE" | sed -n 's/.*[^0-9]\([0-9][0-9]*\) skipped.*/\1/p')
  [ -z "$PASS_COUNT" ] && PASS_COUNT="0"
  [ -z "$FAIL_COUNT" ] && FAIL_COUNT="0"
  [ -n "$SKIPPED" ] && [ "$SKIPPED" != "0" ] && SKIP_INFO=", $SKIPPED skipped"
fi

# Extract failed test names (lines starting with "FAIL " or " x ")
FAILED_LINES=$(grep -E '^\s*(FAIL|x )' "$CLEAN" | head -5 | sed 's/^\s*//' | paste -sd ', ' -)
[ -n "$FAILED_LINES" ] && FAIL_NAMES="; failures: $FAILED_LINES"

if [ "$EXIT_CODE" -eq 0 ]; then
  echo ""
  echo "CHECK_TESTS_RESULT: PASS (${PASS_COUNT} passed${SKIP_INFO})"
else
  echo ""
  echo "CHECK_TESTS_RESULT: FAIL (${FAIL_COUNT} failed, ${PASS_COUNT} passed${SKIP_INFO}${FAIL_NAMES})"
fi

exit $EXIT_CODE
