import path from "node:path";
import fs from "node:fs/promises";
import { writeFileSafe } from "../../core/utils.js";
import { CLARTE_DIR } from "../../core/config/config.js";
import { LEARN } from "../../core/config/thresholds.js";
import type { DetectedContext } from "../../core/types/detection.js";
import type { PersistedGraph } from "../../core/types/persisted-graph.js";

const SCRIPTS_DIR = `${CLARTE_DIR}/scripts`;

/**
 * Resolve the test command for a detected project context.
 * Returns null if no test command can be determined.
 */
export function resolveTestCommand(ctx: DetectedContext): string | null {
  const prefix = (() => {
    switch (ctx.packageManager) {
      case "pnpm":
        return "pnpm";
      case "yarn":
        return "yarn";
      case "bun":
        return "bun run";
      case "npm":
        return "npm run";
      default:
        return null;
    }
  })();

  // JS/TS ecosystem: use package.json scripts.test
  if (prefix) return `${prefix} test`;

  switch (ctx.packageManager) {
    case "pip":
    case "poetry": {
      if (ctx.testFramework === "pytest") {
        return ctx.packageManager === "poetry" ? "poetry run pytest" : "pytest";
      }
      return null;
    }
    case "cargo":
      return "cargo test";
    case "go":
      return "go test ./...";
    default:
      return null;
  }
}

/**
 * Build the check-tests.sh shell script content.
 * The script runs the project's test command and outputs a structured one-line summary.
 */
function buildCheckTestsScript(testCmd: string, framework?: string): string {
  // Framework-specific pass/fail parsing patterns
  const parser = buildParser(framework);
  const fallback = toNpmFallback(testCmd);
  const resolveCmd = fallback
    ? `if command -v ${testCmd.split(" ")[0]} >/dev/null 2>&1; then BASE_CMD="${testCmd}"; else BASE_CMD="${fallback}"; fi`
    : `BASE_CMD="${testCmd}"`;

  return `#!/usr/bin/env bash
# Generated by clarte - do not edit
# Runs tests and outputs a structured one-line summary.
# Usage: .clarte/scripts/check-tests.sh [extra-args...]
set -o pipefail

# Package scripts expect node_modules/.bin on PATH
export PATH="./node_modules/.bin:$PATH"

${resolveCmd}
EXTRA_ARGS="$*"
CMD="$BASE_CMD\${EXTRA_ARGS:+ $EXTRA_ARGS}"

TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT

eval "$CMD" 2>&1 | tee "$TMPFILE"
EXIT_CODE=\${PIPESTATUS[0]}

# Strip ANSI escape codes for reliable parsing
CLEAN=$(mktemp)
trap 'rm -f "$TMPFILE" "$CLEAN"' EXIT
sed 's/\\x1b\\[[0-9;]*m//g' "$TMPFILE" > "$CLEAN"

${parser}

if [ "$EXIT_CODE" -eq 0 ]; then
  echo ""
  echo "CHECK_TESTS_RESULT: PASS (\${PASS_COUNT} passed\${SKIP_INFO})"
else
  echo ""
  echo "CHECK_TESTS_RESULT: FAIL (\${FAIL_COUNT} failed, \${PASS_COUNT} passed\${SKIP_INFO}\${FAIL_NAMES})"
fi

exit $EXIT_CODE
`;
}

/**
 * Build framework-specific output parser for the check-tests script.
 */
function buildParser(framework?: string): string {
  // Common initialization
  const init = `PASS_COUNT="?"
FAIL_COUNT="?"
SKIP_INFO=""
FAIL_NAMES=""`;

  switch (framework) {
    case "Vitest":
      return `${init}

# Vitest output: "Tests  42 passed | 2 failed | 1 skipped (45)"
LINE=$(grep -E 'Tests\\s+[0-9]' "$CLEAN" | tail -1)
if [ -n "$LINE" ]; then
  PASS_COUNT=$(echo "$LINE" | grep -oP '[0-9]+(?=\\s+passed)' || echo "0")
  FAIL_COUNT=$(echo "$LINE" | grep -oP '[0-9]+(?=\\s+failed)' || echo "0")
  SKIPPED=$(echo "$LINE" | grep -oP '[0-9]+(?=\\s+skipped)' || echo "")
  [ -n "$SKIPPED" ] && [ "$SKIPPED" != "0" ] && SKIP_INFO=", $SKIPPED skipped"
fi

# Extract failed test names (lines starting with "FAIL " or " x ")
FAILED_LINES=$(grep -E '^\\s*(FAIL|x )' "$CLEAN" | head -5 | sed 's/^\\s*//' | paste -sd ', ' -)
[ -n "$FAILED_LINES" ] && FAIL_NAMES="; failures: $FAILED_LINES"`;

    case "Jest":
      return `${init}

# Jest output: "Tests:       2 failed, 42 passed, 44 total"
LINE=$(grep -E 'Tests:\\s+' "$CLEAN" | tail -1)
if [ -n "$LINE" ]; then
  PASS_COUNT=$(echo "$LINE" | grep -oP '[0-9]+(?=\\s+passed)' || echo "0")
  FAIL_COUNT=$(echo "$LINE" | grep -oP '[0-9]+(?=\\s+failed)' || echo "0")
  SKIPPED=$(echo "$LINE" | grep -oP '[0-9]+(?=\\s+skipped)' || echo "")
  [ -n "$SKIPPED" ] && [ "$SKIPPED" != "0" ] && SKIP_INFO=", $SKIPPED skipped"
fi

# Extract failed test names (lines with "FAIL " prefix)
FAILED_LINES=$(grep -E '^\\s*FAIL ' "$CLEAN" | head -5 | sed 's/^\\s*FAIL //' | paste -sd ', ' -)
[ -n "$FAILED_LINES" ] && FAIL_NAMES="; failures: $FAILED_LINES"`;

    case "Mocha":
      return `${init}

# Mocha output: "  42 passing" and "  2 failing"
PASS_COUNT=$(grep -oP '[0-9]+(?=\\s+passing)' "$CLEAN" | tail -1 || echo "0")
FAIL_COUNT=$(grep -oP '[0-9]+(?=\\s+failing)' "$CLEAN" | tail -1 || echo "0")
PENDING=$(grep -oP '[0-9]+(?=\\s+pending)' "$CLEAN" | tail -1 || echo "")
[ -n "$PENDING" ] && [ "$PENDING" != "0" ] && SKIP_INFO=", $PENDING pending"

# Extract failed test names (indented lines after "failing")
FAILED_LINES=$(sed -n '/failing/,$ { /^\\s\\+[0-9]\\+)/s/^\\s\\+[0-9]\\+) //p }' "$CLEAN" | head -5 | paste -sd ', ' -)
[ -n "$FAILED_LINES" ] && FAIL_NAMES="; failures: $FAILED_LINES"`;

    case "pytest":
      return `${init}

# pytest output: "5 passed, 2 failed, 1 skipped in 3.45s"
LINE=$(grep -E '[0-9]+ (passed|failed)' "$CLEAN" | tail -1)
if [ -n "$LINE" ]; then
  PASS_COUNT=$(echo "$LINE" | grep -oP '[0-9]+(?=\\s+passed)' || echo "0")
  FAIL_COUNT=$(echo "$LINE" | grep -oP '[0-9]+(?=\\s+failed)' || echo "0")
  SKIPPED=$(echo "$LINE" | grep -oP '[0-9]+(?=\\s+skipped)' || echo "")
  [ -n "$SKIPPED" ] && [ "$SKIPPED" != "0" ] && SKIP_INFO=", $SKIPPED skipped"
fi

# Extract failed test names (FAILED lines)
FAILED_LINES=$(grep -E '^FAILED ' "$CLEAN" | head -5 | sed 's/^FAILED //' | paste -sd ', ' -)
[ -n "$FAILED_LINES" ] && FAIL_NAMES="; failures: $FAILED_LINES"`;

    default:
      // Generic fallback: just report exit code
      return `${init}
# No framework-specific parser. Summary based on exit code only.
if [ "$EXIT_CODE" -eq 0 ]; then
  PASS_COUNT="all"
  FAIL_COUNT="0"
else
  PASS_COUNT="?"
  FAIL_COUNT="some"
fi`;
  }
}

/**
 * Generate the check-tests.sh script in .clarte/scripts/.
 * Returns the relative path if generated, null if no test command detected.
 */
// Matches test scripts that include a pre-compilation step (gulp, tsc, or a compile sub-script).
const SLOW_COMPILE_RE = /\b(gulp|tsc|compile)\b.*&&/;

// Recognizes compile-only segments (gulp, tsc, or pnpm/npm run compile).
export const COMPILE_SEGMENT_RE = /\b(gulp|tsc|compile)\b/;
// Recognizes test runner segments - required to confirm there's actually a test step.
const TEST_SEGMENT_RE = /\b(mocha|jest|vitest|pytest|karma|ava|jasmine)\b|test:(fast|unit|quick|only|run|local)\b/;

/**
 * For test scripts with slow compile steps (e.g. "gulp clean && tsc && mocha"),
 * extract just the test-runner segments (dropping all compile segments).
 * Returns null if no test runner is found or the script has no compile step.
 *
 * Example: "pnpm run compile && pnpm run test:fast --" → "pnpm run test:fast --"
 */
export function extractFastTestCmd(rawTest: string): string | null {
  const parts = rawTest.split("&&").map((p) => p.trim());
  if (parts.length < 2) return null;

  const hasCompile = parts.some((p) => COMPILE_SEGMENT_RE.test(p));
  const testParts = parts.filter((p) => !COMPILE_SEGMENT_RE.test(p));
  if (!hasCompile || testParts.length === 0) return null;
  if (!testParts.some((p) => TEST_SEGMENT_RE.test(p))) return null;

  return testParts.join(" && ");
}

export async function generateCheckTestsScript(rootDir: string, ctx: DetectedContext): Promise<string | null> {
  const testCmd = resolveTestCommand(ctx);
  if (!testCmd) return null;

  const scriptPath = path.join(rootDir, SCRIPTS_DIR, "check-tests.sh");

  // When the test script includes a slow compile step, try to generate a faster variant.
  // If we can't optimize, delete any stale script and bail out so CLAUDE.md won't mention it.
  try {
    const pkg = JSON.parse(await fs.readFile(path.join(rootDir, "package.json"), "utf-8")) as {
      scripts?: Record<string, string>;
    };
    const rawTest = pkg.scripts?.test ?? "";
    if (SLOW_COMPILE_RE.test(rawTest)) {
      const fastCmd = extractFastTestCmd(rawTest);
      if (!fastCmd) {
        // Can't identify a fast test step - remove stale script so CLAUDE.md won't reference it
        try {
          await fs.unlink(scriptPath);
        } catch {}
        return null;
      }
      // Generate check-tests.sh with only the fast test step (no compile).
      // CLAUDE.md tells the agent to compile separately before running this script.
      const scriptContent = buildCheckTestsScript(fastCmd, ctx.testFramework);
      await writeFileSafe(scriptPath, scriptContent);
      await fs.chmod(scriptPath, 0o755);
      return `${SCRIPTS_DIR}/check-tests.sh`;
    }
  } catch {
    // No package.json or unreadable - proceed with generation
  }

  const scriptContent = buildCheckTestsScript(testCmd, ctx.testFramework);
  await writeFileSafe(scriptPath, scriptContent);
  await fs.chmod(scriptPath, 0o755);

  return `${SCRIPTS_DIR}/check-tests.sh`;
}

/**
 * Detect whether tests require compilation and what the compile command is.
 * Checks mocharc spec paths (pointing to build/dist/compiled dirs) and package.json scripts.
 */
async function detectCompileStep(
  rootDir: string,
  ctx: DetectedContext,
): Promise<{ compileCmd: string | null; testsFromCompiled: boolean }> {
  // "run" prefix for arbitrary script names (compile, build, tsc).
  // Unlike lifecycle scripts (test, start), these always need "run".
  const runPrefix = (() => {
    switch (ctx.packageManager) {
      case "pnpm":
        return "pnpm run";
      case "yarn":
        return "yarn run";
      case "bun":
        return "bun run";
      case "npm":
        return "npm run";
      default:
        return null;
    }
  })();

  // Check mocharc for spec paths pointing to compiled output
  if (ctx.testFramework === "Mocha") {
    for (const name of [".mocharc.json", ".mocharc.yaml", ".mocharc.yml", ".mocharc.js", ".mocharc.cjs"]) {
      try {
        const content = await fs.readFile(path.join(rootDir, name), "utf-8");
        // Only parse JSON reliably; YAML/JS just check for build path patterns
        if (name.endsWith(".json")) {
          const rc = JSON.parse(content) as { spec?: string | string[]; file?: string | string[] };
          const specs = Array.isArray(rc.spec) ? rc.spec : rc.spec ? [rc.spec] : [];
          const files = Array.isArray(rc.file) ? rc.file : rc.file ? [rc.file] : [];
          const all = [...specs, ...files];
          if (all.some((s) => /\b(build|dist|compiled|out)\b/.test(s))) {
            // Find the compile script
            if (runPrefix) {
              try {
                const pkg = JSON.parse(await fs.readFile(path.join(rootDir, "package.json"), "utf-8")) as {
                  scripts?: Record<string, string>;
                };
                const scripts = pkg.scripts ?? {};
                const compileKey = ["compile", "build", "tsc"].find((k) => scripts[k]);
                if (compileKey) {
                  return { compileCmd: `${runPrefix} ${compileKey}`, testsFromCompiled: true };
                }
              } catch {}
            }
            return { compileCmd: null, testsFromCompiled: true };
          }
        } else if (/\b(build|dist|compiled|out)\b/.test(content)) {
          return { compileCmd: runPrefix ? `${runPrefix} compile` : null, testsFromCompiled: true };
        }
      } catch {}
    }
  }

  // Check package.json test script for compile step
  if (runPrefix) {
    try {
      const pkg = JSON.parse(await fs.readFile(path.join(rootDir, "package.json"), "utf-8")) as {
        scripts?: Record<string, string>;
      };
      const rawTest = pkg.scripts?.test ?? "";
      if (SLOW_COMPILE_RE.test(rawTest)) {
        // tsc --noEmit is type-checking only; tests don't depend on its output.
        // Only treat it as a real compile step when at least one segment emits files.
        const segments = rawTest.split("&&").map((p) => p.trim());
        const compileSegments = segments.filter((p) => COMPILE_SEGMENT_RE.test(p));
        const emitsFiles = compileSegments.some((p) => !(/\btsc\b/.test(p) && /--noEmit\b/.test(p)));
        if (emitsFiles) {
          const scripts = pkg.scripts ?? {};
          const compileKey = ["compile", "build"].find((k) => scripts[k]);
          return { compileCmd: compileKey ? `${runPrefix} ${compileKey}` : null, testsFromCompiled: true };
        }
      }
    } catch {}
  }

  return { compileCmd: null, testsFromCompiled: false };
}

/**
 * Build the filter flag for a given test framework.
 * Returns the CLI flag that filters tests by name pattern.
 */
function buildTestFilterFlag(framework: string | undefined): string | null {
  switch (framework) {
    case "Mocha":
      return "--grep";
    case "Jest":
    case "Vitest":
      return "-t";
    case "pytest":
      return "-k";
    default:
      return null;
  }
}

/**
 * Replace a non-npm package manager prefix with npm run, for use as a fallback
 * when the detected manager (bun, pnpm, yarn) is not installed at runtime.
 */
function toNpmFallback(cmd: string): string | null {
  const match = cmd.match(/^(bun|pnpm|yarn)(\s+run)?\b/);
  if (!match) return null;
  const pm = match[1];
  // Replace all occurrences of the package manager in the command chain.
  // "bun run X && bun ./build.ts" → "npm run X && npx ./build.ts"
  // Handles: "bun run" → "npm run", standalone "bun" → "npx"
  return cmd.replace(new RegExp(`\\b${pm}\\s+run\\b`, "g"), "npm run").replace(new RegExp(`\\b${pm}\\b`, "g"), "npx");
}

/**
 * Build the run-tests.sh script that compiles (if needed) and runs filtered tests.
 */
function buildRunTestScript(testCmd: string, framework: string | undefined, compileCmd: string | null): string {
  const filterFlag = buildTestFilterFlag(framework);
  // If the test command uses a non-npm package manager, resolve at runtime.
  const testFallback = toNpmFallback(testCmd);
  const safeTestCmd = testFallback ? "$TEST_BASE" : testCmd;
  const testResolve = testFallback
    ? `\nif command -v ${testCmd.split(" ")[0]} >/dev/null 2>&1; then TEST_BASE="${testCmd}"; else TEST_BASE="${testFallback}"; fi`
    : "";
  // Package manager scripts need "--" to pass flags to the underlying runner.
  // Skip if the command already ends with "--" (e.g. extracted fast test commands).
  const needsSeparator = /^(npm run|pnpm|yarn|bun run)\b/.test(testCmd) && !testCmd.trimEnd().endsWith("--");
  const sep = needsSeparator ? "-- " : "";
  // Mocha's --grep interprets the pattern as a regex. Escape metacharacters
  // so test names with parens, brackets etc. match literally.
  const escapeGrep = framework === "Mocha" ? `\nPATTERN=$(printf '%s' "$1" | sed 's/[][(){}.*+?^$|\\\\]/\\\\&/g')` : "";
  const patVar = framework === "Mocha" ? "$PATTERN" : "$1";

  const filterLine = (() => {
    switch (framework) {
      case "Mocha":
      case "Jest":
      case "Vitest":
      case "pytest":
        return `CMD="${safeTestCmd} ${sep}${filterFlag} '${patVar}'"`;
      default:
        // cargo test uses positional, go test uses -run
        if (testCmd.startsWith("cargo")) return `CMD="${safeTestCmd} '$1'"`;
        if (testCmd.startsWith("go")) return `CMD="${safeTestCmd} -run '$1'"`;
        return `CMD="${safeTestCmd} '$1'"`;
    }
  })();

  const compileBlock = (() => {
    if (!compileCmd) return "";
    const fallback = toNpmFallback(compileCmd);
    // If the compile command uses a non-npm package manager, emit a runtime
    // fallback so the script works even when the binary is absent.
    const resolvedCmd = fallback
      ? `if command -v ${compileCmd.split(" ")[0]} >/dev/null 2>&1; then COMPILE="${compileCmd}"; else COMPILE="${fallback}"; fi`
      : `COMPILE="${compileCmd}"`;
    return `
# Compile before running tests (this project runs tests from compiled output)
${resolvedCmd}
echo "[run-test] Compiling..."
eval "$COMPILE" 2>&1 | tail -3
if [ $? -ne 0 ]; then
  echo "Compilation failed. Fix errors before running tests."
  exit 1
fi
echo ""
`;
  })();

  return `#!/usr/bin/env bash
# Generated by clarte - do not edit
# Runs a filtered subset of tests by name pattern.
# Usage: .clarte/scripts/run-tests.sh '<pattern>'
# Example: .clarte/scripts/run-tests.sh 'simple enum'
set -euo pipefail

# Package scripts expect node_modules/.bin on PATH
export PATH="./node_modules/.bin:$PATH"

if [ $# -eq 0 ]; then
  echo "Usage: .clarte/scripts/run-tests.sh '<pattern>'"
  echo "Runs tests matching the given name pattern."
  exit 1
fi
${compileBlock}${testResolve}${escapeGrep}
${filterLine}
eval "$CMD"
`;
}

/**
 * Generate the run-tests.sh script in .clarte/scripts/.
 * Returns the relative path if generated, null if no test command or filter mechanism detected.
 */
export async function generateRunTestScript(rootDir: string, ctx: DetectedContext): Promise<string | null> {
  // Only generate for frameworks where we know the filter mechanism
  const filterFlag = buildTestFilterFlag(ctx.testFramework);
  const isPositionalFilter = ctx.packageManager === "cargo" || ctx.packageManager === "go";
  if (!filterFlag && !isPositionalFilter) return null;

  // Resolve the fast test command (without compile step)
  let testCmd: string | null = null;
  if (ctx.packageManager && !["pip", "poetry", "cargo", "go"].includes(ctx.packageManager)) {
    try {
      const pkg = JSON.parse(await fs.readFile(path.join(rootDir, "package.json"), "utf-8")) as {
        scripts?: Record<string, string>;
      };
      const rawTest = pkg.scripts?.test ?? "";
      if (SLOW_COMPILE_RE.test(rawTest)) {
        testCmd = extractFastTestCmd(rawTest);
      }
    } catch {}
  }
  if (!testCmd) {
    testCmd = resolveTestCommand(ctx);
  }
  if (!testCmd) return null;

  const { compileCmd } = await detectCompileStep(rootDir, ctx);

  const scriptContent = buildRunTestScript(testCmd, ctx.testFramework, compileCmd);
  const scriptPath = path.join(rootDir, SCRIPTS_DIR, "run-tests.sh");
  await writeFileSafe(scriptPath, scriptContent);
  await fs.chmod(scriptPath, 0o755);

  return `${SCRIPTS_DIR}/run-tests.sh`;
}

/** Per-file graph data baked into the clarte-grep script at generate time. */
interface GrepGraphEntry {
  importers: string[];
  coChanges: Array<[string, number]>;
  testFile: string | null;
}

/**
 * Build the per-file lookup table from a persisted graph.
 * Only includes files that have at least one piece of graph data.
 */
function buildGrepGraphData(graph: PersistedGraph): Record<string, GrepGraphEntry> {
  // Build reverse edge index: target -> importers
  const importersByTarget = new Map<string, string[]>();
  for (const edge of graph.edges) {
    let list = importersByTarget.get(edge.to);
    if (!list) {
      list = [];
      importersByTarget.set(edge.to, list);
    }
    list.push(edge.from);
  }

  const data: Record<string, GrepGraphEntry> = {};

  for (const filePath of Object.keys(graph.files)) {
    const record = graph.files[filePath];
    const importers = importersByTarget.get(filePath) ?? [];

    const coChanges: Array<[string, number]> = graph.changeCoupling
      .filter((c) => (c.fileA === filePath || c.fileB === filePath) && c.confidence >= LEARN.COCHANGE_THRESHOLD)
      .sort((a, b) => b.confidence - a.confidence)
      .slice(0, 3)
      .map((c) => {
        const partner = c.fileA === filePath ? c.fileB : c.fileA;
        return [partner, Math.round(c.confidence * 100)] as [string, number];
      });

    const testFiles = record.testFiles ?? [];
    const testFile = testFiles.length > 0 ? testFiles[0] : null;

    // Skip files with no graph data worth surfacing
    if (importers.length === 0 && coChanges.length === 0 && testFile === null) continue;

    data[filePath] = { importers, coChanges, testFile };
  }

  return data;
}

/**
 * Build the clarte-grep shell script content with baked-in graph data.
 */
function buildClarteGrepScript(graphData: Record<string, GrepGraphEntry>): string {
  const json = JSON.stringify(graphData);

  return `#!/usr/bin/env bash
# Generated by clarte - do not edit
# Wraps rg and appends graph context (importers, co-changes, test file) for each matching file.
# Usage: .clarte/scripts/clarte-grep <pattern> [rg args...]

GRAPH_DATA='${json.replace(/'/g, "'\\''")}'

if ! command -v rg &>/dev/null; then
  echo "clarte-grep: rg (ripgrep) not found in PATH" >&2
  exit 1
fi

rg --with-filename "$@" | node -e "
const lines = require('fs').readFileSync(0, 'utf-8').split('\\n');
const data = JSON.parse(process.env.GRAPH_DATA || '{}');

let lastFile = null;

for (let i = 0; i < lines.length; i++) {
  const line = lines[i];
  // rg output with --with-filename: path:line:content or path:content
  const m = line.match(/^([^:]+):[0-9]+:/);
  const file = m ? m[1] : null;

  if (file && file !== lastFile) {
    // Emit annotation for the previous file before switching
    if (lastFile !== null) {
      const entry = data[lastFile];
      if (entry) {
        const parts = [];
        if (entry.importers && entry.importers.length > 0) {
          parts.push('importers: ' + entry.importers.slice(0, 5).join(', ') + (entry.importers.length > 5 ? ' (+' + (entry.importers.length - 5) + ' more)' : ''));
        }
        if (entry.coChanges && entry.coChanges.length > 0) {
          parts.push('co-changes: ' + entry.coChanges.map(function(c) { return c[0] + ' (' + c[1] + '%)'; }).join(', '));
        }
        if (entry.testFile) {
          parts.push('test: ' + entry.testFile);
        }
        if (parts.length > 0) {
          process.stdout.write('  \u21b3 ' + parts.join(' | ') + '\\n');
        }
      }
    }
    lastFile = file;
  }

  if (line !== '' || i < lines.length - 1) {
    process.stdout.write(line + '\\n');
  }
}

// Emit annotation for the last file
if (lastFile !== null) {
  const entry = data[lastFile];
  if (entry) {
    const parts = [];
    if (entry.importers && entry.importers.length > 0) {
      parts.push('importers: ' + entry.importers.slice(0, 5).join(', ') + (entry.importers.length > 5 ? ' (+' + (entry.importers.length - 5) + ' more)' : ''));
    }
    if (entry.coChanges && entry.coChanges.length > 0) {
      parts.push('co-changes: ' + entry.coChanges.map(function(c) { return c[0] + ' (' + c[1] + '%)'; }).join(', '));
    }
    if (entry.testFile) {
      parts.push('test: ' + entry.testFile);
    }
    if (parts.length > 0) {
      process.stdout.write('  \u21b3 ' + parts.join(' | ') + '\\n');
    }
  }
}
" GRAPH_DATA="$GRAPH_DATA"
`;
}

/**
 * Generate the clarte-grep script in .clarte/scripts/ with baked-in graph data.
 * Returns the relative path on success.
 */
export async function generateClarteGrepScript(rootDir: string, graph: PersistedGraph): Promise<string> {
  const graphData = buildGrepGraphData(graph);
  const scriptContent = buildClarteGrepScript(graphData);
  const scriptPath = path.join(rootDir, SCRIPTS_DIR, "clarte-grep");

  await writeFileSafe(scriptPath, scriptContent);
  await fs.chmod(scriptPath, 0o755);

  return `${SCRIPTS_DIR}/clarte-grep`;
}
