import { execSync } from "node:child_process";
import { readdir, readFile, unlink } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { readJsonFile, writeFileSafe } from "../../core/utils";
import { CLARTE_DIR } from "../../core/config/config";
import { PRE_FLIGHT_AGENT_CONTENT } from "../context/pre-flight-agent";

const HOOKS_DIR = `${CLARTE_DIR}/hooks`;
const SETTINGS_PATH = ".claude/settings.json";

const PARSE_STDIN = `let input;
try { input = JSON.parse(readFileSync(0, "utf-8")); } catch { process.exit(0); }`;

const SESSION_START_SCRIPT = `#!/usr/bin/env node
// Generated by clarte - do not edit
import { readFileSync, appendFileSync, writeFileSync, rmSync, mkdirSync, statSync, renameSync } from "node:fs";
import { resolve } from "node:path";

const _debug = !!process.env.CLARTE_DEBUG;
function _dbg(msg) { if (_debug) process.stderr.write("[clarte] " + msg + "\\n"); }

${PARSE_STDIN}
const model = (input.model || "").toLowerCase();
if (model.includes("haiku") && process.env.CLAUDE_ENV_FILE) {
  appendFileSync(process.env.CLAUDE_ENV_FILE, "export CLARTE_HOOKS_DISABLED=1\\n");
}

const cwd = input.cwd || process.cwd();
const STATE_DIR = resolve(cwd, ".clarte/hooks/.state");

// ── Prediction feedback loop: compare previous session's predictions vs edits ──
try {
  const pred = JSON.parse(readFileSync(resolve(STATE_DIR, "predictions.json"), "utf-8"));
  const edits = JSON.parse(readFileSync(resolve(STATE_DIR, "edits.json"), "utf-8"));
  if (pred.targets && pred.targets.length > 0 && edits.files && edits.files.length > 0) {
    const predicted = new Set(pred.targets);
    const edited = new Set(edits.files);
    const hits = pred.targets.filter(t => edited.has(t));
    const precision = hits.length / predicted.size;
    const recall = hits.length / edited.size;
    const entry = {
      timestamp: pred.timestamp,
      query: pred.query,
      predicted: pred.targets,
      edited: edits.files,
      hits,
      precision: Math.round(precision * 1000) / 1000,
      recall: Math.round(recall * 1000) / 1000,
    };
    mkdirSync(STATE_DIR, { recursive: true });
    // Rotate log at 1MB to prevent unbounded growth
    const logPath = resolve(STATE_DIR, "prediction-log.jsonl");
    try { if (statSync(logPath).size > 1_000_000) renameSync(logPath, logPath.replace(".jsonl", "-" + Date.now() + ".jsonl")); } catch (e) { _dbg("log rotation: " + e.message); }
    appendFileSync(logPath, JSON.stringify(entry) + "\\n");
  }
} catch (e) { _dbg("prediction feedback: " + e.message); }

// Always reset hook state on every new session start
try { rmSync(resolve(STATE_DIR, "fail-fast.json"), { force: true }); } catch (e) { _dbg("cleanup fail-fast: " + e.message); }
try { rmSync(resolve(STATE_DIR, "pre-flight.json"), { force: true }); } catch (e) { _dbg("cleanup pre-flight: " + e.message); }
try { rmSync(resolve(STATE_DIR, "predictions.json"), { force: true }); } catch (e) { _dbg("cleanup predictions: " + e.message); }
try { rmSync(resolve(STATE_DIR, "edits.json"), { force: true }); } catch (e) { _dbg("cleanup edits: " + e.message); }

// Check if generated hooks/scripts are stale (different clarte version)
try {
  const versionFile = resolve(cwd, ".clarte/version");
  const installed = readFileSync(versionFile, "utf-8").trim();
  const { execSync } = await import("node:child_process");
  const current = execSync("npx clarte --version", { encoding: "utf-8", timeout: 5000 }).trim();
  if (installed && current && installed !== current) {
    process.stderr.write("[clarte] Hooks were generated by v" + installed + " but v" + current + " is installed. Run npx clarte --yes to regenerate.\\n");
  }
} catch (e) { _dbg("version check: " + e.message); }
`;

const FAIL_FAST_SCRIPT = `#!/usr/bin/env node
// Generated by clarte - do not edit
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve } from "node:path";

if (process.env.CLARTE_HOOKS_DISABLED) process.exit(0);

${PARSE_STDIN}
const tool = input.tool_name;
if (!tool) process.exit(0);

const cwd = input.cwd || process.cwd();
const STATE_DIR = resolve(cwd, ".clarte/hooks/.state");
const FF_STATE = STATE_DIR + "/fail-fast.json";
const THRESHOLD = 3;
const TEST_RE = /\\b(npm\\s+test|npm\\s+run\\s+test|pnpm\\s+(run\\s+)?test|yarn\\s+test|bun\\s+(run\\s+)?test|npx\\s+(vitest|jest|mocha)|vitest|jest|mocha|pytest|cargo\\s+test|go\\s+test)\\b/;
const BUILD_RE = /\\b(npm\\s+run\\s+(build|compile)|pnpm\\s+(run\\s+)?(build|compile)|yarn\\s+(run\\s+)?(build|compile)|tsc(\\s|$)|npx\\s+tsc|pnpm\\s+exec\\s+tsc)\\b/;
const debug = process.env.CLARTE_HOOK_DEBUG === "1";

function log(msg) { if (debug) process.stderr.write("[fail-fast] " + msg + "\\n"); }

function readFFState() {
  try { return JSON.parse(readFileSync(FF_STATE, "utf-8")); } catch { return { base: "", count: 0 }; }
}

function writeFFState(state) {
  try { mkdirSync(STATE_DIR, { recursive: true }); writeFileSync(FF_STATE, JSON.stringify(state)); } catch (e) { log("state write: " + e.message); }
}

function extractBase(cmd) {
  return cmd.split("|")[0].replace(/\\s*2>&1\\s*$/, "").trim();
}

if (tool !== "Bash" && tool !== "Edit" && tool !== "Write") process.exit(0);

if (existsSync(resolve(cwd, ".clarte/fail-fast-override"))) {
  log("override file found, skipping");
  process.exit(0);
}


if (tool === "Edit" || tool === "Write") {
  log("edit/write detected, resetting state");
  writeFFState({ base: "", count: 0 });
  process.exit(0);
}

if (tool === "Bash") {
  const cmd = input.tool_input?.command || "";
  const isTest = TEST_RE.test(cmd);
  const isBuild = BUILD_RE.test(cmd);
  if (isTest || isBuild) {
    const base = extractBase(cmd);
    const state = readFFState();
    if (state.base === base) {
      state.count += 1;
    } else {
      state.base = base;
      state.count = 1;
    }
    const kind = isTest ? "test" : "build";
    log(kind + " #" + state.count + " base: " + base.slice(0, 80));
    writeFFState(state);
    if (state.count >= THRESHOLD) {
      const output = JSON.stringify({
        hookSpecificOutput: {
          hookEventName: "PreToolUse",
          permissionDecision: "deny",
          permissionDecisionReason: "Blocked: you have run the same " + kind + " command " + state.count + " times with no code edits in between. The output will not change. Re-read the existing output and try a different approach, or create .clarte/fail-fast-override to disable this check."
        }
      });
      process.stdout.write(output);
      process.exit(0);
    }
  } else {
    // Non-test/build Bash (scripts, installs, etc.) may change file state,
    // so reset the counter. Read-only commands (grep, cat) cause a harmless
    // extra reset, but that's preferable to false-blocking after a legit fix.
    log("non-test bash, resetting state");
    writeFFState({ base: "", count: 0 });
  }
}
`;

// ── Pre-flight budget limiter ─────────────────────────────────────────────────
// Two hooks work together:
// 1. SubagentStart (matcher: clarte-pre-flight) records the agent_id in state
// 2. PreToolUse checks if agent_id matches and enforces a tool-call limit
//
// When the limit is hit, the hook denies with a message telling the agent to
// return what it has. This is a graceful degradation: the agent sees the deny
// reason and can output partial findings rather than being abruptly killed.

const PRE_FLIGHT_START_SCRIPT = `#!/usr/bin/env node
// Generated by clarte - do not edit
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";

if (process.env.CLARTE_HOOKS_DISABLED) process.exit(0);

${PARSE_STDIN}
const agentId = input.agent_id;
if (!agentId) process.exit(0);

const cwd = input.cwd || process.cwd();
const STATE_DIR = resolve(cwd, ".clarte/hooks/.state");
const PF_STATE = STATE_DIR + "/pre-flight.json";

try {
  mkdirSync(STATE_DIR, { recursive: true });
  writeFileSync(PF_STATE, JSON.stringify({ agentId, calls: 0 }));
} catch (e) { process.stderr.write("[clarte] pre-flight start: " + e.message + "\\n"); }
`;

const PRE_FLIGHT_LIMIT = 10;

const PRE_FLIGHT_LIMITER_SCRIPT = `#!/usr/bin/env node
// Generated by clarte - do not edit
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";

if (process.env.CLARTE_HOOKS_DISABLED) process.exit(0);

${PARSE_STDIN}
const agentId = input.agent_id;
if (!agentId) process.exit(0);

const cwd = input.cwd || process.cwd();
const STATE_DIR = resolve(cwd, ".clarte/hooks/.state");
const PF_STATE = STATE_DIR + "/pre-flight.json";

let state;
try { state = JSON.parse(readFileSync(PF_STATE, "utf-8")); } catch { process.exit(0); }

// Only act on tool calls from the tracked pre-flight agent
if (state.agentId !== agentId) process.exit(0);

state.calls += 1;
try { mkdirSync(STATE_DIR, { recursive: true }); writeFileSync(PF_STATE, JSON.stringify(state)); } catch (e) { process.stderr.write("[clarte] pre-flight state: " + e.message + "\\n"); }

if (state.calls > ${PRE_FLIGHT_LIMIT}) {
  const output = JSON.stringify({
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: "Pre-flight budget reached (${PRE_FLIGHT_LIMIT} tool calls). Stop reading and return your findings now. Output what you have - partial findings with UNCERTAIN flags are fine."
    }
  });
  process.stdout.write(output);
}
`;

// ── Edit tracker for prediction feedback loop ──────────────────────────────────
// PostToolUse hook on Edit/Write: records which files were actually modified.
// At next session start, predictions are compared against edits for precision/recall.

const EDIT_TRACKER_SCRIPT = `#!/usr/bin/env node
// Generated by clarte - do not edit
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";

if (process.env.CLARTE_HOOKS_DISABLED) process.exit(0);

${PARSE_STDIN}
const tool = input.tool_name;
if (tool !== "Edit" && tool !== "Write") process.exit(0);

const filePath = input.tool_input?.file_path;
if (!filePath || typeof filePath !== "string") process.exit(0);

const cwd = input.cwd || process.cwd();
const STATE_DIR = resolve(cwd, ".clarte/hooks/.state");
const EDITS_FILE = STATE_DIR + "/edits.json";

let state;
try { state = JSON.parse(readFileSync(EDITS_FILE, "utf-8")); } catch { state = { files: [] }; }

// Store relative path for comparison against predictions (which use relative paths)
let rel = filePath;
if (filePath.startsWith(cwd)) rel = filePath.slice(cwd.length).replace(/^\\//, "");
if (!state.files.includes(rel)) state.files.push(rel);

try {
  mkdirSync(STATE_DIR, { recursive: true });
  writeFileSync(EDITS_FILE, JSON.stringify(state));
} catch (e) { process.stderr.write("[clarte] edit tracker: " + e.message + "\\n"); }
`;

interface HookDef {
  event: string;
  file: string;
  matcher?: string;
  script: string;
}

const PROMPT_SCRIPT = `#!/usr/bin/env node
// Generated by clarte - do not edit
import { readFileSync, writeFileSync, mkdirSync, existsSync, unlinkSync, copyFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { resolve } from "node:path";
import { resolveEditTargets, rankSymbols, shouldSkipPreFlight, promptMentionsTargets,
         renderTaskContext, renderFallbackContext, resolveTargetsFromHistory } from "./bm25f.mjs";

if (process.env.CLARTE_HOOKS_DISABLED) process.exit(0);
const _debug = !!process.env.CLARTE_DEBUG;
function _dbg(msg) { if (_debug) process.stderr.write("[clarte] " + msg + "\\n"); }

${PARSE_STDIN}
const prompt = input.prompt;
if (shouldSkipPreFlight(prompt)) process.exit(0);

const root = process.cwd();
const STATE_DIR = resolve(root, ".clarte/hooks/.state");
const tcPath = resolve(root, ".clarte/task-context.md");
const agentSrc = resolve(root, ".clarte/agents/clarte-pre-flight.md");
const agentDst = resolve(root, ".claude/agents/clarte-pre-flight.md");
try { unlinkSync(tcPath); } catch (e) { _dbg("cleanup: " + e.message); }
try { unlinkSync(agentDst); } catch (e) { _dbg("cleanup: " + e.message); }

const dbPath = resolve(root, ".clarte/graph.db");
if (existsSync(dbPath)) {
  let graph;
  try {
    // Load graph from SQLite. Try bun:sqlite first (Bun built-in), then better-sqlite3.
    let db;
    try {
      const bsq = await import("bun:sqlite");
      db = new bsq.Database(dbPath, { readonly: true });
    } catch {
      try {
        const { createRequire } = await import("node:module");
        const req = createRequire(import.meta.url);
        const Bsq = req("better-sqlite3");
        db = new Bsq(dbPath, { readonly: true });
      } catch { _dbg("no SQLite binding available"); }
    }
    if (db) {
      graph = loadGraphFromDb(db);
      try { db.close(); } catch {}
    }
  } catch (e) { _dbg("graph: " + e.message); }
  if (graph) {
    const allCandidates = resolveEditTargets(prompt, graph, 10);
    const targets = allCandidates.slice(0, 5);
    const runnersUp = allCandidates.slice(5);
    if (targets.length > 0) {
      if (promptMentionsTargets(prompt, targets)) process.exit(0);

      const lastMod = new Map();
      for (const fp of targets) {
        try {
          const age = execSync("git log -1 --format='%cr' -- " + JSON.stringify(fp),
            { cwd: root, encoding: "utf-8", timeout: 1000 }).trim();
          if (age) lastMod.set(fp, age);
        } catch (e) { _dbg("git: " + e.message); }
      }

      const symbols = rankSymbols(targets, graph, prompt);
      const content = renderTaskContext(targets, runnersUp, graph, symbols, lastMod);

      try {
        mkdirSync(resolve(root, ".clarte"), { recursive: true });
        writeFileSync(tcPath, content);
        if (existsSync(agentSrc)) {
          mkdirSync(resolve(root, ".claude/agents"), { recursive: true });
          copyFileSync(agentSrc, agentDst);
        }
      } catch (e) { _dbg("write: " + e.message); }

      try {
        mkdirSync(STATE_DIR, { recursive: true });
        writeFileSync(resolve(STATE_DIR, "predictions.json"),
          JSON.stringify({ timestamp: new Date().toISOString(), query: prompt.slice(0, 500), targets, symbols: Object.fromEntries(symbols) }));
      } catch (e) { _dbg("predict: " + e.message); }
      process.exit(0);
    }
  }
}

function loadGraphFromDb(db) {
  const fileRows = db.prepare("SELECT path, hash, role, authority, hub_score, betweenness, instability, community_id, is_chokepoint, separates_components, is_cross_cutting, layer_spread, has_tests, layers, test_files, intra_file_calls FROM files").all();
  const edgeRows = db.prepare("SELECT from_path, to_path, imported_names, is_type_only, is_dynamic, is_barrel_routed FROM file_edges").all();
  const communities = db.prepare("SELECT id, label FROM communities").all();
  const changeCoupling = db.prepare("SELECT file_a, file_b, co_changes, confidence FROM change_coupling").all();
  const symbolRows = db.prepare("SELECT file_path, name, kind, start_line, authority, body_tokens FROM symbols").all();

  const files = Object.create(null);
  const reverseEdges = Object.create(null);
  for (const row of fileRows) {
    const layers = row.layers ? JSON.parse(row.layers) : [];
    const testFiles = row.test_files ? JSON.parse(row.test_files) : [];
    const intraFileCalls = row.intra_file_calls ? JSON.parse(row.intra_file_calls) : [];
    files[row.path] = {
      role: row.role || null,
      authority: row.authority || 0,
      hubScore: row.hub_score || 0,
      betweenness: row.betweenness || 0,
      instability: row.instability !== null ? row.instability : null,
      importedByCount: 0,
      isChokepoint: row.is_chokepoint === 1,
      separatesComponents: row.separates_components || 0,
      isCrossCutting: row.is_cross_cutting === 1,
      layerSpread: row.layer_spread || 0,
      layers,
      hasTests: row.has_tests === 1,
      testFiles,
      communityId: row.community_id !== null ? row.community_id : null,
      intraFileCalls,
    };
    reverseEdges[row.path] = [];
  }

  const edges = [];
  for (const row of edgeRows) {
    const importedNames = row.imported_names ? JSON.parse(row.imported_names) : [];
    edges.push({ from: row.from_path, to: row.to_path, importedNames, isTypeOnly: row.is_type_only === 1, isDynamic: row.is_dynamic === 1, isBarrelRouted: row.is_barrel_routed === 1 });
    if (files[row.to_path]) files[row.to_path].importedByCount++;
    if (!reverseEdges[row.to_path]) reverseEdges[row.to_path] = [];
    reverseEdges[row.to_path].push(row.from_path);
  }

  // Attach symbol data
  for (const sym of symbolRows) {
    const f = files[sym.file_path];
    if (!f) continue;
    if (!f.symbolNames) f.symbolNames = [];
    f.symbolNames.push(sym.name);
    if (sym.body_tokens) {
      if (!f.symbolBodyTokens) f.symbolBodyTokens = Object.create(null);
      f.symbolBodyTokens[sym.name] = sym.body_tokens.split(" ").filter(Boolean);
    }
    if (sym.start_line > 0) {
      if (!f.symbolStartLines) f.symbolStartLines = Object.create(null);
      f.symbolStartLines[sym.name] = sym.start_line;
    }
    if (sym.authority !== null) {
      if (!f.symbolAuthority) f.symbolAuthority = Object.create(null);
      f.symbolAuthority[sym.name] = sym.authority;
    }
  }

  const communityFiles = Object.create(null);
  for (const row of fileRows) {
    if (row.community_id !== null) {
      if (!communityFiles[row.community_id]) communityFiles[row.community_id] = [];
      communityFiles[row.community_id].push(row.path);
    }
  }

  return {
    version: 1,
    timestamp: new Date().toISOString(),
    files,
    edges,
    communities: communities.map(c => ({ id: c.id, files: communityFiles[c.id] || [], label: c.label || String(c.id) })),
    changeCoupling: changeCoupling.map(c => ({ fileA: c.file_a, fileB: c.file_b, confidence: c.confidence, coChangeCount: c.co_changes })),
    structuralMismatches: [],
    testMapping: {},
    lagCouplings: [],
  };
}

// Fallback: git history BM25 (no graph available)
const fallback = resolveTargetsFromHistory(prompt, root, 5);
if (fallback) {
  try {
    mkdirSync(resolve(root, ".clarte"), { recursive: true });
    writeFileSync(tcPath, renderFallbackContext(fallback.files, fallback.commitMessage));
    if (existsSync(agentSrc)) {
      mkdirSync(resolve(root, ".claude/agents"), { recursive: true });
      copyFileSync(agentSrc, agentDst);
    }
  } catch (e) { _dbg("fallback: " + e.message); }
}
`;

const HOOK_DEFS: HookDef[] = [
  { event: "SessionStart", file: "on-session-start.mjs", script: SESSION_START_SCRIPT },
  { event: "PreToolUse", file: "on-fail-fast.mjs", script: FAIL_FAST_SCRIPT },
  { event: "PreToolUse", file: "on-pre-flight-limit.mjs", script: PRE_FLIGHT_LIMITER_SCRIPT },
  {
    event: "SubagentStart",
    file: "on-pre-flight-start.mjs",
    matcher: "clarte-pre-flight",
    script: PRE_FLIGHT_START_SCRIPT,
  },
  { event: "PostToolUse", file: "on-edit-tracker.mjs", script: EDIT_TRACKER_SCRIPT },
  { event: "UserPromptSubmit", file: "on-prompt.mjs", script: PROMPT_SCRIPT },
];

// All events that may have had clarte hooks (including legacy PostToolUse) - always clean these up
const ALL_HOOK_EVENTS = ["SessionStart", "PreToolUse", "PostToolUse", "SubagentStart", "UserPromptSubmit"];

/**
 * Generate hook script files in .clarte/hooks/.
 * Copies the pre-built scoring bundle (bm25f.mjs) and writes all hook scripts.
 */
export async function generateHookFiles(rootDir: string): Promise<void> {
  const hooksDir = path.join(rootDir, HOOKS_DIR);

  // Copy pre-built scoring bundle from dist/
  const thisDir = path.dirname(fileURLToPath(import.meta.url));
  const bundleSrc = path.join(thisDir, "hook-entry.mjs");
  try {
    const bundleContent = await readFile(bundleSrc, "utf-8");
    await writeFileSafe(path.join(hooksDir, "bm25f.mjs"), bundleContent);
  } catch {
    // Bundle may not exist in dev mode; hooks will fail gracefully at runtime
  }

  for (const def of HOOK_DEFS) {
    await writeFileSafe(path.join(hooksDir, def.file), def.script);
  }

  // Remove stale hook files from previous versions
  const knownFiles = new Set([...HOOK_DEFS.map((d) => d.file), "bm25f.mjs", ".state"]);
  try {
    const entries = await readdir(hooksDir);
    for (const entry of entries) {
      if (!knownFiles.has(entry)) {
        await unlink(path.join(hooksDir, entry)).catch(() => {});
      }
    }
  } catch {}

  // Write version marker so the session-start hook can detect staleness
  try {
    const { VERSION } = await import("../../cli/args.js");
    await writeFileSafe(path.join(rootDir, CLARTE_DIR, "version"), VERSION + "\n");
  } catch {}
}

/**
 * Generate the pre-flight diagnostic agent file at .clarte/agents/clarte-pre-flight.md.
 * The on-prompt hook copies it to .claude/agents/ on demand when the prompt is opaque.
 */
export async function generatePreFlightAgentFile(rootDir: string): Promise<void> {
  const agentsDir = path.join(rootDir, ".clarte", "agents");
  await writeFileSafe(path.join(agentsDir, "clarte-pre-flight.md"), PRE_FLIGHT_AGENT_CONTENT);
}

interface HookEntry {
  type: string;
  command: string;
}

interface MatchedHookGroup {
  matcher?: string;
  hooks: HookEntry[];
}

interface ClaudeSettings {
  hooks?: {
    PreToolUse?: MatchedHookGroup[];
    PostToolUse?: MatchedHookGroup[];
    SessionStart?: MatchedHookGroup[];
    [key: string]: unknown;
  };
  [key: string]: unknown;
}

function isClarteHook(entry: MatchedHookGroup): boolean {
  return entry.hooks?.some((h) => h.command?.includes(`${HOOKS_DIR}/`)) ?? false;
}

function upsertHookEntry(entries: MatchedHookGroup[], newEntry: MatchedHookGroup, hookFile: string): void {
  const existingIdx = entries.findIndex((entry) =>
    entry.hooks?.some((h) => h.command?.endsWith(`${HOOKS_DIR}/${hookFile}`)),
  );
  if (existingIdx >= 0) {
    entries[existingIdx] = newEntry;
  } else {
    entries.push(newEntry);
  }
}

function detectHookRunner(): string {
  try {
    execSync("bun --version", { stdio: "ignore" });
    return "bun";
  } catch {
    return "node";
  }
}

/**
 * Configure Claude Code hook settings in .claude/settings.json.
 * Merges SessionStart and PreToolUse hooks without clobbering user-defined hooks.
 */
export async function configureClaudeHooks(rootDir: string): Promise<void> {
  const settingsPath = path.join(rootDir, SETTINGS_PATH);
  const raw = (await readJsonFile(settingsPath)) as ClaudeSettings | null;
  const settings: ClaudeSettings = raw ?? {};

  if (!settings.hooks) {
    settings.hooks = {};
  }

  // Clean up all existing clarte hooks across all known events (including legacy PostToolUse).
  for (const event of ALL_HOOK_EVENTS) {
    const group = settings.hooks[event] as MatchedHookGroup[] | undefined;
    if (group) {
      settings.hooks[event] = group.filter((entry) => !isClarteHook(entry));
    }
  }

  // bun has built-in SQLite (bun:sqlite), needed by on-prompt.mjs for graph loading.
  // node falls back to git-history-based target resolution (no SQLite binding).
  const runner = detectHookRunner();

  // Insert fresh hooks
  for (const def of HOOK_DEFS) {
    const group = (settings.hooks[def.event] ??= []) as MatchedHookGroup[];
    const entry: MatchedHookGroup = {
      ...(def.matcher ? { matcher: def.matcher } : {}),
      hooks: [{ type: "command", command: `${runner} ${HOOKS_DIR}/${def.file}` }],
    };
    upsertHookEntry(group, entry, def.file);
  }

  await writeFileSafe(settingsPath, JSON.stringify(settings, null, 2) + "\n");
}
