import type { CodeSnapshot, DetectedContext, UserAnswers } from "../types.js";
import { summarizeDetection } from "../detect.js";
import { getFrameworkHints } from "./framework-hints.js";

/**
 * Build an Aider config file (.aider.conf.yml) with project conventions.
 * Aider uses YAML format with a `conventions` key containing a list of strings.
 */
export function buildAiderContext(
  ctx: DetectedContext,
  answers: UserAnswers,
  snapshot: CodeSnapshot | null,
): string {
  const lines: string[] = [];

  lines.push("# .aider.conf.yml — Generated by context-pilot");
  lines.push("# Keep this file up to date as the project evolves.");
  lines.push("");

  const stackSummary = answers.stackConfirmed
    ? summarizeDetection(ctx)
    : answers.stackCorrections || summarizeDetection(ctx);

  // Conventions as a YAML list
  lines.push("conventions:");
  lines.push(`  - "Project: ${escapeYaml(answers.projectPurpose)}"`);
  lines.push(`  - "Stack: ${escapeYaml(stackSummary)}"`);

  // Frameworks
  if (ctx.frameworks.length > 0) {
    const fws = ctx.frameworks
      .map((f) => `${f.name}${f.version ? ` ${f.version}` : ""}`)
      .join(", ");
    lines.push(`  - "Frameworks: ${escapeYaml(fws)}"`);
  }

  // Package manager + linter
  if (ctx.packageManager !== "none") {
    lines.push(`  - "Package manager: ${ctx.packageManager}"`);
  }
  if (ctx.linter !== "none") {
    lines.push(`  - "Linter: ${ctx.linter}"`);
  }

  // Project structure
  if (ctx.directories.length > 0) {
    const dirs = ctx.directories.join(", ");
    lines.push(`  - "Key directories: ${escapeYaml(dirs)}"`);
  }

  // Key patterns
  if (answers.keyPatterns) {
    const patterns = answers.keyPatterns
      .split(/[.\n]/)
      .map((s) => s.trim())
      .filter(Boolean);
    for (const p of patterns) {
      lines.push(`  - "${escapeYaml(p)}"`);
    }
  }

  // Gotchas
  if (answers.gotchas) {
    const gotchas = answers.gotchas
      .split(/[.\n]/)
      .map((s) => s.trim())
      .filter(Boolean);
    for (const g of gotchas) {
      lines.push(`  - "GOTCHA: ${escapeYaml(g)}"`);
    }
  }

  // Framework conventions
  const fwHints = getFrameworkHints(ctx);
  if (fwHints.length > 0) {
    // Filter to just the bullet-point lines (skip headers and blank lines)
    for (const hint of fwHints) {
      const trimmed = hint.trim();
      if (trimmed && trimmed.startsWith("- ")) {
        lines.push(`  - "${escapeYaml(trimmed.slice(2))}"`);
      }
    }
  }

  // Monorepo info
  if (ctx.monorepo && ctx.monorepo.packages.length > 0) {
    lines.push(
      `  - "Monorepo: ${ctx.monorepo.type} with ${ctx.monorepo.packages.length} packages"`,
    );
    for (const pkg of ctx.monorepo.packages) {
      const fws =
        pkg.frameworks.length > 0
          ? ` (${pkg.frameworks.map((f) => f.name).join(", ")})`
          : "";
      lines.push(`  - "Package: ${escapeYaml(pkg.name)} at ${escapeYaml(pkg.path)}${escapeYaml(fws)}"`);
    }
  }

  // Code snapshot
  if (snapshot?.markdown) {
    lines.push("");
    lines.push(
      "# CODE SNAPSHOT (auto-generated, update when types/stores/services change)",
    );
    lines.push("# Formatted as a multi-line read block for Aider context.");
    lines.push("read:");
    // We can't inline markdown directly into YAML conventions cleanly.
    // Instead, write a companion markdown file and reference it.
    // For now, include the snapshot as a YAML comment block.
    lines.push(
      "  # To include the code snapshot, create a file and add it here:",
    );
    lines.push("  # - .aider.context.md");

    // Also add the snapshot as commented YAML for reference
    lines.push("");
    lines.push("# --- Code Snapshot (for reference) ---");
    for (const line of snapshot.markdown.split("\n")) {
      lines.push(`# ${line}`);
    }
    lines.push("# --- /Code Snapshot ---");
  }

  lines.push("");

  return lines.join("\n");
}

/**
 * Escape a string for use inside double-quoted YAML values.
 */
function escapeYaml(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}
