import type { CodeSnapshot, ContextAnalysis, DetectedContext, UserAnswers } from "../types.js";
import { summarizeDetection } from "../detect/detect.js";
import { getFrameworkHints } from "./framework-hints.js";
import { renderConstraintsSection } from "../config/scan.js";
import { renderConventionsSection } from "../conventions/conventions.js";
import { renderTestMappingSection } from "../analysis/test-map.js";
import { buildDirectives, computeFileComplexity } from "./directives.js";

/**
 * Build an Aider config file (.aider.conf.yml) with project conventions.
 * Aider uses YAML format with a `conventions` key containing a list of strings.
 */
export async function buildAiderContext(
  ctx: DetectedContext,
  answers: UserAnswers,
  snapshot: CodeSnapshot | null,
  analysis?: ContextAnalysis,
): Promise<string> {
  const lines: string[] = [];

  lines.push("# .aider.conf.yml - Generated by clarte");
  lines.push("# Keep this file up to date as the project evolves.");
  lines.push("");

  const stackSummary = answers.stackConfirmed
    ? summarizeDetection(ctx)
    : answers.stackCorrections || summarizeDetection(ctx);

  // Conventions as a YAML list
  lines.push("conventions:");
  if (answers.projectPurpose) {
    lines.push(`  - "Project: ${escapeYaml(answers.projectPurpose)}"`);
  }
  lines.push(`  - "Stack: ${escapeYaml(stackSummary)}"`);
  lines.push(
    `  - "INSTRUCTION: This file is your starting point. Only read additional files when the task requires details not captured here."`,
  );

  // Frameworks
  if (ctx.frameworks.length > 0) {
    const fws = ctx.frameworks.map((f) => `${f.name}${f.version ? ` ${f.version}` : ""}`).join(", ");
    lines.push(`  - "Frameworks: ${escapeYaml(fws)}"`);
  }

  // Package manager + linter
  if (ctx.packageManager !== "none") {
    lines.push(`  - "Package manager: ${ctx.packageManager}"`);
  }
  if (ctx.linter !== "none") {
    lines.push(`  - "Linter: ${ctx.linter}"`);
  }

  // Config constraints
  if (analysis?.configConstraints) {
    const constraintsSection = renderConstraintsSection(analysis.configConstraints);
    if (constraintsSection) {
      lines.push(...markdownBulletsToYaml(constraintsSection));
    }
  }

  // Inferred conventions
  if (analysis?.conventions) {
    const conventionsSection = renderConventionsSection(analysis.conventions);
    if (conventionsSection) {
      lines.push(...markdownBulletsToYaml(conventionsSection));
    }
  }

  // Test mapping
  if (analysis?.testMapping) {
    const testSection = renderTestMappingSection(analysis.testMapping, analysis?.hubFiles);
    if (testSection) {
      lines.push(...markdownBulletsToYaml(testSection));
    }
  }

  // Project structure
  if (ctx.directories.length > 0) {
    const dirs = ctx.directories.join(", ");
    lines.push(`  - "Key directories: ${escapeYaml(dirs)}"`);
  }

  // Key patterns
  if (answers.keyPatterns) {
    const patterns = answers.keyPatterns
      .split(/\n/)
      .map((s) => s.trim())
      .filter(Boolean);
    for (const p of patterns) {
      lines.push(`  - "${escapeYaml(p)}"`);
    }
  }

  // Gotchas
  if (answers.gotchas) {
    const gotchas = answers.gotchas
      .split(/\n/)
      .map((s) => s.trim())
      .filter(Boolean);
    for (const g of gotchas) {
      lines.push(`  - "GOTCHA: ${escapeYaml(g)}"`);
    }
  }

  // Framework conventions
  const fwHints = getFrameworkHints(ctx);
  if (fwHints.length > 0) {
    for (const hint of fwHints) {
      const trimmed = hint.trim();
      if (trimmed?.startsWith("- ")) {
        lines.push(`  - "${escapeYaml(trimmed.slice(2))}"`);
      }
    }
  }

  // Working guidelines (analysis-derived directives)
  if (analysis) {
    const fileComplexity = analysis.hubFiles?.length
      ? await computeFileComplexity(ctx.rootDir, analysis.hubFiles)
      : undefined;
    const directives = buildDirectives(analysis, ctx, fileComplexity);
    for (const d of directives) {
      lines.push(`  - "GUIDELINE: ${escapeYaml(d)}"`);
    }
  }

  // Monorepo info
  if (ctx.monorepo && ctx.monorepo.packages.length > 0) {
    lines.push(`  - "Monorepo: ${ctx.monorepo.type} with ${ctx.monorepo.packages.length} packages"`);
    for (const pkg of ctx.monorepo.packages) {
      const fws = pkg.frameworks.length > 0 ? ` (${pkg.frameworks.map((f) => f.name).join(", ")})` : "";
      lines.push(`  - "Package: ${escapeYaml(pkg.name)} at ${escapeYaml(pkg.path)}${escapeYaml(fws)}"`);
    }
  }

  // Key files
  if (analysis?.hubFiles && analysis.hubFiles.length > 0) {
    const fileDescs = analysis.hubFiles.map((h) => `${h.path} (${h.role})`).join(", ");
    lines.push(`  - "Key files (read these first for architecture): ${escapeYaml(fileDescs)}"`);
  }

  // Architecture
  if (analysis?.layers && analysis.layers.length > 1) {
    const flow = analysis.layers.map((l) => l.name).join(" → ");
    lines.push(`  - "Architecture dependency flow: ${escapeYaml(flow)}"`);
  }

  // Instability warnings
  if (analysis?.instabilities && analysis.instabilities.length > 0) {
    for (const inst of analysis.instabilities) {
      lines.push(
        `  - "UNSTABLE: ${escapeYaml(inst.path)}: ${(inst.instability * 100).toFixed(0)}% unstable (${inst.fanIn} dependents, ${inst.fanOut} deps)"`,
      );
    }
  }

  // Change coupling
  if (analysis?.gitActivity?.changeCoupling && analysis.gitActivity.changeCoupling.length > 0) {
    for (const pair of analysis.gitActivity.changeCoupling.slice(0, 5)) {
      const ab = pair.confidenceAB ?? pair.confidence;
      const ba = pair.confidenceBA ?? pair.confidence;
      if (ab >= 0.6 && ba < 0.6) {
        lines.push(
          `  - "CO-CHANGE: ${escapeYaml(pair.fileA)} -> ${escapeYaml(pair.fileB)} (${pair.coChangeCount} co-changes, A->B ${(ab * 100).toFixed(0)}%)"`,
        );
      } else if (ba >= 0.6 && ab < 0.6) {
        lines.push(
          `  - "CO-CHANGE: ${escapeYaml(pair.fileB)} -> ${escapeYaml(pair.fileA)} (${pair.coChangeCount} co-changes, B->A ${(ba * 100).toFixed(0)}%)"`,
        );
      } else {
        lines.push(
          `  - "CO-CHANGE: ${escapeYaml(pair.fileA)} <-> ${escapeYaml(pair.fileB)} (${pair.coChangeCount} co-changes, ${(pair.confidence * 100).toFixed(0)}% confidence)"`,
        );
      }
    }
  }

  // Cross-cutting files
  if (analysis?.crossCuttingFiles && analysis.crossCuttingFiles.length > 0) {
    for (const f of analysis.crossCuttingFiles) {
      lines.push(
        `  - "CROSS-CUTTING: ${escapeYaml(f.file)} spans ${f.layerSpread} layers (${escapeYaml(f.layers.join(", "))}), changes have wide blast radius"`,
      );
    }
  }

  // Layer consistency violations
  if (analysis?.layerConsistency && analysis.layerConsistency.violations.length > 0) {
    const pct = (analysis.layerConsistency.consistency * 100).toFixed(0);
    lines.push(`  - "LAYER ORDER: ${pct}% consistent. Do not introduce upward dependency violations."`);
    for (const v of analysis.layerConsistency.violations.slice(0, 3)) {
      lines.push(
        `  - "VIOLATION: ${escapeYaml(v.from)} (${escapeYaml(v.fromLayer)}) imports ${escapeYaml(v.to)} (${escapeYaml(v.toLayer)})"`,
      );
    }
  }

  // Chokepoints
  if (analysis?.chokepoints && analysis.chokepoints.length > 0) {
    for (const cp of analysis.chokepoints.slice(0, 5)) {
      const count = cp.upstreamCount;
      lines.push(
        `  - "CHOKEPOINT: ${escapeYaml(cp.file)} has ${count} transitive dependents, refactor with extreme care"`,
      );
    }
  }

  // Dead files
  if (analysis?.deadFiles && analysis.deadFiles.length > 0) {
    for (const deadFile of analysis.deadFiles.slice(0, 5)) {
      lines.push(`  - "DEAD FILE: ${escapeYaml(deadFile)} has no importers. Consider removing."`);
    }
  }

  // Structural mismatches (hidden coupling)
  if (analysis?.structuralMismatches && analysis.structuralMismatches.length > 0) {
    for (const m of analysis.structuralMismatches.slice(0, 3)) {
      lines.push(
        `  - "HIDDEN COUPLING: ${escapeYaml(m.fileA)} and ${escapeYaml(m.fileB)} change together but have no import link. Consider adding an explicit dependency."`,
      );
    }
  }

  // Monorepo cross-package analysis
  if (analysis?.monorepoAnalysis && analysis.monorepoAnalysis.crossPackageEdges.length > 0) {
    const mono = analysis.monorepoAnalysis;
    lines.push(
      `  - "MONOREPO: ${mono.crossPackageEdges.length} cross-package edge(s), ${mono.encapsulationViolations.length} encapsulation violation(s)"`,
    );
    for (const v of mono.encapsulationViolations.slice(0, 3)) {
      lines.push(
        `  - "ENCAPSULATION: ${escapeYaml(v.from)} imports internal file ${escapeYaml(v.to)} from ${escapeYaml(v.toPackage)}. Use the public API instead."`,
      );
    }
  }

  // Circular dependencies
  if (analysis?.circularDeps && analysis.circularDeps.length > 0) {
    for (const dep of analysis.circularDeps) {
      const severity =
        dep.severity != null ? (dep.severity === 0 ? " [type-only]" : dep.severity < 1 ? " [mixed]" : "") : "";
      const hint = dep.breakHint ? ` -- ${escapeYaml(dep.breakHint)}` : "";
      lines.push(`  - "CIRCULAR DEP: ${escapeYaml(dep.chain.join(" -> "))}${severity}${hint}"`);
    }
  }

  // Recently active files
  if (analysis?.gitActivity && analysis.gitActivity.hotFiles.length > 0) {
    const hot = analysis.gitActivity.hotFiles
      .slice(0, 5)
      .map((h) => `${h.path} (${h.commits} commits)`)
      .join(", ");
    lines.push(`  - "Recently active: ${escapeYaml(hot)}"`);
  }

  // Code snapshot
  if (snapshot?.markdown) {
    lines.push("");
    lines.push("# CODE SNAPSHOT (auto-generated, update when types/stores/services change)");
    lines.push("# Formatted as a multi-line read block for Aider context.");
    lines.push("read:");
    // We can't inline markdown directly into YAML conventions cleanly.
    // Instead, write a companion markdown file and reference it.
    // For now, include the snapshot as a YAML comment block.
    lines.push("  # To include the code snapshot, create a file and add it here:");
    lines.push("  # - .aider.context.md");

    // Also add the snapshot as commented YAML for reference
    lines.push("");
    lines.push("# --- Code Snapshot (for reference) ---");
    for (const line of snapshot.markdown.split("\n")) {
      lines.push(`# ${line}`);
    }
    lines.push("# --- /Code Snapshot ---");
  }

  lines.push("");

  return lines.join("\n");
}

/**
 * Escape a string for use inside double-quoted YAML values.
 */
function escapeYaml(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n").replace(/\t/g, "\\t");
}

/**
 * Convert a markdown bullet list section to indented YAML list entries.
 */
function markdownBulletsToYaml(section: string): string[] {
  return section
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.startsWith("- "))
    .map((line) => `  - "${escapeYaml(line.slice(2).replace(/\*\*/g, ""))}"`);
}
