import path from "node:path";
import fs from "node:fs/promises";
import { writeFileSafe } from "../utils.js";
import { CLARTE_DIR } from "../config/config.js";
import type { DetectedContext } from "../types/detection.js";
import type { PersistedGraph } from "../types/persisted-graph.js";

const SCRIPTS_DIR = `${CLARTE_DIR}/scripts`;

/**
 * Resolve the test command for a detected project context.
 * Returns null if no test command can be determined.
 */
export function resolveTestCommand(ctx: DetectedContext): string | null {
  const prefix = (() => {
    switch (ctx.packageManager) {
      case "pnpm":
        return "pnpm";
      case "yarn":
        return "yarn";
      case "bun":
        return "bun run";
      case "npm":
        return "npm run";
      default:
        return null;
    }
  })();

  // JS/TS ecosystem: use package.json scripts.test
  if (prefix) return `${prefix} test`;

  switch (ctx.packageManager) {
    case "pip":
    case "poetry": {
      if (ctx.testFramework === "pytest") {
        return ctx.packageManager === "poetry" ? "poetry run pytest" : "pytest";
      }
      return null;
    }
    case "cargo":
      return "cargo test";
    case "go":
      return "go test ./...";
    default:
      return null;
  }
}

/**
 * Build the check-tests.sh shell script content.
 * The script runs the project's test command and outputs a structured one-line summary.
 */
function buildCheckTestsScript(testCmd: string, framework?: string): string {
  // Framework-specific pass/fail parsing patterns
  const parser = buildParser(framework);

  return `#!/usr/bin/env bash
# Generated by clarte - do not edit
# Runs tests and outputs a structured one-line summary.
# Usage: .clarte/scripts/check-tests.sh [extra-args...]
set -o pipefail

EXTRA_ARGS="\$*"
CMD="${testCmd}\${EXTRA_ARGS:+ \$EXTRA_ARGS}"

TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT

eval "$CMD" 2>&1 | tee "$TMPFILE"
EXIT_CODE=\${PIPESTATUS[0]}

# Strip ANSI escape codes for reliable parsing
CLEAN=$(mktemp)
trap 'rm -f "$TMPFILE" "$CLEAN"' EXIT
sed 's/\\x1b\\[[0-9;]*m//g' "$TMPFILE" > "$CLEAN"

${parser}

if [ "$EXIT_CODE" -eq 0 ]; then
  echo ""
  echo "CHECK_TESTS_RESULT: PASS (\${PASS_COUNT} passed\${SKIP_INFO})"
else
  echo ""
  echo "CHECK_TESTS_RESULT: FAIL (\${FAIL_COUNT} failed, \${PASS_COUNT} passed\${SKIP_INFO}\${FAIL_NAMES})"
fi

exit $EXIT_CODE
`;
}

/**
 * Build framework-specific output parser for the check-tests script.
 */
function buildParser(framework?: string): string {
  // Common initialization
  const init = `PASS_COUNT="?"
FAIL_COUNT="?"
SKIP_INFO=""
FAIL_NAMES=""`;

  switch (framework) {
    case "Vitest":
      return `${init}

# Vitest output: "Tests  42 passed | 2 failed | 1 skipped (45)"
LINE=$(grep -E 'Tests\\s+[0-9]' "$CLEAN" | tail -1)
if [ -n "$LINE" ]; then
  PASS_COUNT=$(echo "$LINE" | grep -oP '[0-9]+(?=\\s+passed)' || echo "0")
  FAIL_COUNT=$(echo "$LINE" | grep -oP '[0-9]+(?=\\s+failed)' || echo "0")
  SKIPPED=$(echo "$LINE" | grep -oP '[0-9]+(?=\\s+skipped)' || echo "")
  [ -n "$SKIPPED" ] && [ "$SKIPPED" != "0" ] && SKIP_INFO=", $SKIPPED skipped"
fi

# Extract failed test names (lines starting with "FAIL " or " x ")
FAILED_LINES=$(grep -E '^\\s*(FAIL|x )' "$CLEAN" | head -5 | sed 's/^\\s*//' | paste -sd ', ' -)
[ -n "$FAILED_LINES" ] && FAIL_NAMES="; failures: $FAILED_LINES"`;

    case "Jest":
      return `${init}

# Jest output: "Tests:       2 failed, 42 passed, 44 total"
LINE=$(grep -E 'Tests:\\s+' "$CLEAN" | tail -1)
if [ -n "$LINE" ]; then
  PASS_COUNT=$(echo "$LINE" | grep -oP '[0-9]+(?=\\s+passed)' || echo "0")
  FAIL_COUNT=$(echo "$LINE" | grep -oP '[0-9]+(?=\\s+failed)' || echo "0")
  SKIPPED=$(echo "$LINE" | grep -oP '[0-9]+(?=\\s+skipped)' || echo "")
  [ -n "$SKIPPED" ] && [ "$SKIPPED" != "0" ] && SKIP_INFO=", $SKIPPED skipped"
fi

# Extract failed test names (lines with "FAIL " prefix)
FAILED_LINES=$(grep -E '^\\s*FAIL ' "$CLEAN" | head -5 | sed 's/^\\s*FAIL //' | paste -sd ', ' -)
[ -n "$FAILED_LINES" ] && FAIL_NAMES="; failures: $FAILED_LINES"`;

    case "Mocha":
      return `${init}

# Mocha output: "  42 passing" and "  2 failing"
PASS_COUNT=$(grep -oP '[0-9]+(?=\\s+passing)' "$CLEAN" | tail -1 || echo "0")
FAIL_COUNT=$(grep -oP '[0-9]+(?=\\s+failing)' "$CLEAN" | tail -1 || echo "0")
PENDING=$(grep -oP '[0-9]+(?=\\s+pending)' "$CLEAN" | tail -1 || echo "")
[ -n "$PENDING" ] && [ "$PENDING" != "0" ] && SKIP_INFO=", $PENDING pending"

# Extract failed test names (indented lines after "failing")
FAILED_LINES=$(sed -n '/failing/,$ { /^\\s\\+[0-9]\\+)/s/^\\s\\+[0-9]\\+) //p }' "$CLEAN" | head -5 | paste -sd ', ' -)
[ -n "$FAILED_LINES" ] && FAIL_NAMES="; failures: $FAILED_LINES"`;

    case "pytest":
      return `${init}

# pytest output: "5 passed, 2 failed, 1 skipped in 3.45s"
LINE=$(grep -E '[0-9]+ (passed|failed)' "$CLEAN" | tail -1)
if [ -n "$LINE" ]; then
  PASS_COUNT=$(echo "$LINE" | grep -oP '[0-9]+(?=\\s+passed)' || echo "0")
  FAIL_COUNT=$(echo "$LINE" | grep -oP '[0-9]+(?=\\s+failed)' || echo "0")
  SKIPPED=$(echo "$LINE" | grep -oP '[0-9]+(?=\\s+skipped)' || echo "")
  [ -n "$SKIPPED" ] && [ "$SKIPPED" != "0" ] && SKIP_INFO=", $SKIPPED skipped"
fi

# Extract failed test names (FAILED lines)
FAILED_LINES=$(grep -E '^FAILED ' "$CLEAN" | head -5 | sed 's/^FAILED //' | paste -sd ', ' -)
[ -n "$FAILED_LINES" ] && FAIL_NAMES="; failures: $FAILED_LINES"`;

    default:
      // Generic fallback: just report exit code
      return `${init}
# No framework-specific parser. Summary based on exit code only.
if [ "$EXIT_CODE" -eq 0 ]; then
  PASS_COUNT="all"
  FAIL_COUNT="0"
else
  PASS_COUNT="?"
  FAIL_COUNT="some"
fi`;
  }
}

/**
 * Generate the check-tests.sh script in .clarte/scripts/.
 * Returns the relative path if generated, null if no test command detected.
 */
// Matches test scripts that include a pre-compilation step (gulp, tsc, or a compile sub-script).
// Running these repeatedly is slow (60s+) and unreliable as a quick check.
const SLOW_COMPILE_RE = /\b(gulp|tsc|compile)\b.*&&/;

export async function generateCheckTestsScript(
  rootDir: string,
  ctx: DetectedContext,
): Promise<string | null> {
  const testCmd = resolveTestCommand(ctx);
  if (!testCmd) return null;

  // Skip generation when the raw test script includes a slow compile step.
  // The agent would invoke `pnpm test` which triggers a 60s+ build, making
  // check-tests.sh harmful rather than helpful.
  try {
    const pkg = JSON.parse(await fs.readFile(path.join(rootDir, "package.json"), "utf-8")) as {
      scripts?: Record<string, string>;
    };
    const rawTest = pkg.scripts?.test ?? "";
    if (SLOW_COMPILE_RE.test(rawTest)) return null;
  } catch {
    // No package.json or unreadable - proceed with generation
  }

  const scriptContent = buildCheckTestsScript(testCmd, ctx.testFramework);
  const scriptPath = path.join(rootDir, SCRIPTS_DIR, "check-tests.sh");

  await writeFileSafe(scriptPath, scriptContent);
  await fs.chmod(scriptPath, 0o755);

  return `${SCRIPTS_DIR}/check-tests.sh`;
}

/** Per-file graph data baked into the clarte-grep script at generate time. */
interface GrepGraphEntry {
  importers: string[];
  coChanges: Array<[string, number]>;
  testFile: string | null;
}

const CO_CHANGE_THRESHOLD = 0.4;

/**
 * Build the per-file lookup table from a persisted graph.
 * Only includes files that have at least one piece of graph data.
 */
function buildGrepGraphData(graph: PersistedGraph): Record<string, GrepGraphEntry> {
  // Build reverse edge index: target -> importers
  const importersByTarget = new Map<string, string[]>();
  for (const edge of graph.edges) {
    let list = importersByTarget.get(edge.to);
    if (!list) {
      list = [];
      importersByTarget.set(edge.to, list);
    }
    list.push(edge.from);
  }

  const data: Record<string, GrepGraphEntry> = {};

  for (const filePath of Object.keys(graph.files)) {
    const record = graph.files[filePath];
    const importers = importersByTarget.get(filePath) ?? [];

    const coChanges: Array<[string, number]> = graph.changeCoupling
      .filter(
        (c) =>
          (c.fileA === filePath || c.fileB === filePath) && c.confidence >= CO_CHANGE_THRESHOLD,
      )
      .sort((a, b) => b.confidence - a.confidence)
      .slice(0, 3)
      .map((c) => {
        const partner = c.fileA === filePath ? c.fileB : c.fileA;
        return [partner, Math.round(c.confidence * 100)] as [string, number];
      });

    const testFiles = record.testFiles ?? [];
    const testFile = testFiles.length > 0 ? testFiles[0] : null;

    // Skip files with no graph data worth surfacing
    if (importers.length === 0 && coChanges.length === 0 && testFile === null) continue;

    data[filePath] = { importers, coChanges, testFile };
  }

  return data;
}

/**
 * Build the clarte-grep shell script content with baked-in graph data.
 */
function buildClarteGrepScript(graphData: Record<string, GrepGraphEntry>): string {
  const json = JSON.stringify(graphData);

  return `#!/usr/bin/env bash
# Generated by clarte - do not edit
# Wraps rg and appends graph context (importers, co-changes, test file) for each matching file.
# Usage: .clarte/scripts/clarte-grep <pattern> [rg args...]

GRAPH_DATA='${json.replace(/'/g, "'\\''")}'

if ! command -v rg &>/dev/null; then
  echo "clarte-grep: rg (ripgrep) not found in PATH" >&2
  exit 1
fi

rg --with-filename "$@" | node -e "
const lines = require('fs').readFileSync(0, 'utf-8').split('\\n');
const data = JSON.parse(process.env.GRAPH_DATA || '{}');

let lastFile = null;

for (let i = 0; i < lines.length; i++) {
  const line = lines[i];
  // rg output with --with-filename: path:line:content or path:content
  const m = line.match(/^([^:]+):[0-9]+:/);
  const file = m ? m[1] : null;

  if (file && file !== lastFile) {
    // Emit annotation for the previous file before switching
    if (lastFile !== null) {
      const entry = data[lastFile];
      if (entry) {
        const parts = [];
        if (entry.importers && entry.importers.length > 0) {
          parts.push('importers: ' + entry.importers.slice(0, 5).join(', ') + (entry.importers.length > 5 ? ' (+' + (entry.importers.length - 5) + ' more)' : ''));
        }
        if (entry.coChanges && entry.coChanges.length > 0) {
          parts.push('co-changes: ' + entry.coChanges.map(function(c) { return c[0] + ' (' + c[1] + '%)'; }).join(', '));
        }
        if (entry.testFile) {
          parts.push('test: ' + entry.testFile);
        }
        if (parts.length > 0) {
          process.stdout.write('  \u21b3 ' + parts.join(' | ') + '\\n');
        }
      }
    }
    lastFile = file;
  }

  if (line !== '' || i < lines.length - 1) {
    process.stdout.write(line + '\\n');
  }
}

// Emit annotation for the last file
if (lastFile !== null) {
  const entry = data[lastFile];
  if (entry) {
    const parts = [];
    if (entry.importers && entry.importers.length > 0) {
      parts.push('importers: ' + entry.importers.slice(0, 5).join(', ') + (entry.importers.length > 5 ? ' (+' + (entry.importers.length - 5) + ' more)' : ''));
    }
    if (entry.coChanges && entry.coChanges.length > 0) {
      parts.push('co-changes: ' + entry.coChanges.map(function(c) { return c[0] + ' (' + c[1] + '%)'; }).join(', '));
    }
    if (entry.testFile) {
      parts.push('test: ' + entry.testFile);
    }
    if (parts.length > 0) {
      process.stdout.write('  \u21b3 ' + parts.join(' | ') + '\\n');
    }
  }
}
" GRAPH_DATA="$GRAPH_DATA"
`;
}

/**
 * Generate the clarte-grep script in .clarte/scripts/ with baked-in graph data.
 * Returns the relative path on success.
 */
export async function generateClarteGrepScript(
  rootDir: string,
  graph: PersistedGraph,
): Promise<string> {
  const graphData = buildGrepGraphData(graph);
  const scriptContent = buildClarteGrepScript(graphData);
  const scriptPath = path.join(rootDir, SCRIPTS_DIR, "clarte-grep");

  await writeFileSafe(scriptPath, scriptContent);
  await fs.chmod(scriptPath, 0o755);

  return `${SCRIPTS_DIR}/clarte-grep`;
}
