import path from "node:path";
import { readJsonFile, writeFileSafe } from "../utils.js";
import type { PersistedGraph } from "../types/persisted-graph.js";
import { buildContextMap } from "./context-map.js";
import { CLARTE_DIR } from "../config/config.js";

const HOOKS_DIR = `${CLARTE_DIR}/hooks`;
const CONTEXT_MAP_FILE = "context-map.json";
const SETTINGS_PATH = ".claude/settings.json";

const PARSE_STDIN = `let input;
try { input = JSON.parse(readFileSync("/dev/stdin", "utf-8")); } catch { process.exit(0); }`;

const SESSION_START_SCRIPT = `#!/usr/bin/env node
// Generated by clarte - do not edit
import { readFileSync, appendFileSync, rmSync } from "node:fs";

${PARSE_STDIN}
const model = (input.model || "").toLowerCase();
if (model.includes("haiku") && process.env.CLAUDE_ENV_FILE) {
  appendFileSync(process.env.CLAUDE_ENV_FILE, "export CLARTE_HOOKS_DISABLED=1\\n");
}
try { rmSync(".clarte/hooks/.state", { recursive: true, force: true }); } catch {}
`;

const READ_SCRIPT = `#!/usr/bin/env node
// Generated by clarte - do not edit
import { readFileSync } from "node:fs";
import { resolve, relative } from "node:path";

if (process.env.CLARTE_HOOKS_DISABLED) process.exit(0);

${PARSE_STDIN}
const filePath = input.tool_input?.file_path;
if (!filePath) process.exit(0);

const root = process.cwd();
const rel = relative(root, resolve(filePath));
const mapPath = resolve(root, ".clarte/hooks/context-map.json");

let map;
try { map = JSON.parse(readFileSync(mapPath, "utf-8")); } catch { process.exit(0); }

const ctx = map[rel] || map[rel.replace(/\\\\/g, "/")];
if (!ctx) process.exit(0);

const output = JSON.stringify({ additionalContext: ctx });
process.stdout.write(output);
`;

const FAIL_FAST_SCRIPT = `#!/usr/bin/env node
// Generated by clarte - do not edit
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";

if (process.env.CLARTE_HOOKS_DISABLED) process.exit(0);

${PARSE_STDIN}
const tool = input.tool_name;
if (!tool) process.exit(0);

const STATE_DIR = ".clarte/hooks/.state";
const STATE_FILE = STATE_DIR + "/fail-fast.json";
const THRESHOLD = 5;
const TEST_RE = /\\b(npm\\s+test|npm\\s+run\\s+test|pnpm\\s+(run\\s+)?test|yarn\\s+test|bun\\s+test|npx\\s+(vitest|jest)|vitest|jest|pytest|cargo\\s+test|go\\s+test)\\b/;
const debug = process.env.CLARTE_HOOK_DEBUG === "1";

function log(msg) { if (debug) process.stderr.write("[fail-fast] " + msg + "\\n"); }

function readState() {
  try { return JSON.parse(readFileSync(STATE_FILE, "utf-8")); } catch { return { count: 0 }; }
}

function writeState(state) {
  try { mkdirSync(STATE_DIR, { recursive: true }); writeFileSync(STATE_FILE, JSON.stringify(state)); } catch {}
}

if (tool !== "Bash" && tool !== "Edit" && tool !== "Write") process.exit(0);

if (existsSync(".clarte/fail-fast-override")) {
  log("override file found, skipping");
  process.exit(0);
}

if (tool === "Edit" || tool === "Write") {
  log("edit/write detected, resetting counter");
  writeState({ count: 0 });
  process.exit(0);
}

if (tool === "Bash") {
  const cmd = input.tool_input?.command || "";
  if (TEST_RE.test(cmd)) {
    const state = readState();
    state.count = (state.count || 0) + 1;
    log("test command #" + state.count + ": " + cmd.slice(0, 80));
    writeState(state);
    if (state.count >= THRESHOLD) {
      const output = JSON.stringify({
        hookSpecificOutput: {
          hookEventName: "PreToolUse",
          permissionDecision: "deny",
          permissionDecisionReason: "Blocked: " + state.count + " consecutive test commands with no code edits between them. Re-read the test output and try a different approach. Run any non-test command to reset, or create .clarte/fail-fast-override to disable this check."
        }
      });
      process.stdout.write(output);
      process.exit(0);
    }
  } else {
    log("non-test bash, resetting counter");
    writeState({ count: 0 });
  }
}
`;

interface HookDef {
  event: string;
  file: string;
  matcher?: string;
  script: string;
}

const HOOK_DEFS: HookDef[] = [
  { event: "SessionStart", file: "on-session-start.mjs", script: SESSION_START_SCRIPT },
  { event: "PreToolUse", file: "on-read.mjs", matcher: "Read", script: READ_SCRIPT },
  { event: "PreToolUse", file: "on-fail-fast.mjs", script: FAIL_FAST_SCRIPT },
];

/**
 * Generate hook files: context-map.json, on-read.mjs and on-session-start.mjs.
 * When enriched=true, includes extra context (instability, layers, tight coupling).
 * Pass directives for per-file directive injection.
 */
export async function generateHookFiles(
  rootDir: string,
  graph: PersistedGraph,
  enriched?: boolean,
  directives?: string[],
): Promise<void> {
  const contextMap = buildContextMap(graph, enriched, directives);

  const hooksDir = path.join(rootDir, HOOKS_DIR);
  await writeFileSafe(path.join(hooksDir, CONTEXT_MAP_FILE), JSON.stringify(contextMap, null, 2));
  for (const def of HOOK_DEFS) {
    await writeFileSafe(path.join(hooksDir, def.file), def.script);
  }
}

interface HookEntry {
  type: string;
  command: string;
}

interface MatchedHookGroup {
  matcher?: string;
  hooks: HookEntry[];
}

interface ClaudeSettings {
  hooks?: {
    PreToolUse?: MatchedHookGroup[];
    SessionStart?: MatchedHookGroup[];
    [key: string]: unknown;
  };
  [key: string]: unknown;
}

function isClartHook(entry: MatchedHookGroup): boolean {
  return entry.hooks?.some((h) => h.command?.includes(`${HOOKS_DIR}/`)) ?? false;
}

function upsertHookEntry(entries: MatchedHookGroup[], newEntry: MatchedHookGroup, hookFile: string): void {
  const existingIdx = entries.findIndex((entry) =>
    entry.hooks?.some((h) => h.command?.endsWith(`${HOOKS_DIR}/${hookFile}`)),
  );
  if (existingIdx >= 0) {
    entries[existingIdx] = newEntry;
  } else {
    entries.push(newEntry);
  }
}

/**
 * Configure Claude Code hook settings in .claude/settings.json.
 * Merges SessionStart and PreToolUse hooks without clobbering user-defined hooks.
 */
export async function configureClaudeHooks(rootDir: string): Promise<void> {
  const settingsPath = path.join(rootDir, SETTINGS_PATH);
  const raw = (await readJsonFile(settingsPath)) as ClaudeSettings | null;
  const settings: ClaudeSettings = raw ?? {};

  if (!settings.hooks) {
    settings.hooks = {};
  }

  // Clean up all existing clarte hooks first (repairs clobber corruption)
  for (const def of HOOK_DEFS) {
    const group = settings.hooks[def.event] as MatchedHookGroup[] | undefined;
    if (group) {
      settings.hooks[def.event] = group.filter((entry) => !isClartHook(entry));
    }
  }

  // Insert fresh hooks
  for (const def of HOOK_DEFS) {
    const group = (settings.hooks[def.event] ??= []) as MatchedHookGroup[];
    const entry: MatchedHookGroup = {
      ...(def.matcher ? { matcher: def.matcher } : {}),
      hooks: [{ type: "command", command: `node ${HOOKS_DIR}/${def.file}` }],
    };
    upsertHookEntry(group, entry, def.file);
  }

  await writeFileSafe(settingsPath, JSON.stringify(settings, null, 2) + "\n");
}
