import path from "node:path";
import os from "node:os";
import { readJsonFile, writeFileSafe } from "../utils.js";
import type { PersistedGraph } from "../types/persisted-graph.js";
import { buildContextMap } from "./context-map.js";
import { CLARTE_DIR } from "../config/config.js";

const HOOKS_DIR = `${CLARTE_DIR}/hooks`;
const CONTEXT_MAP_FILE = "context-map.json";
const SETTINGS_PATH = ".claude/settings.json";
const PRE_FLIGHT_DONE = `.clarte/hooks/.state/pre-flight-done`;

const PARSE_STDIN = `let input;
try { input = JSON.parse(readFileSync(0, "utf-8")); } catch { process.exit(0); }`;

const SESSION_START_SCRIPT = `#!/usr/bin/env node
// Generated by clarte - do not edit
import { readFileSync, appendFileSync, rmSync } from "node:fs";
import { resolve } from "node:path";

${PARSE_STDIN}
const model = (input.model || "").toLowerCase();
if (model.includes("haiku") && process.env.CLAUDE_ENV_FILE) {
  appendFileSync(process.env.CLAUDE_ENV_FILE, "export CLARTE_HOOKS_DISABLED=1\\n");
}

const cwd = input.cwd || process.cwd();
const STATE_DIR = resolve(cwd, ".clarte/hooks/.state");

// Always reset fail-fast and pre-flight state on every new session start
try { rmSync(resolve(STATE_DIR, "fail-fast.json"), { force: true }); } catch {}
try { rmSync(resolve(STATE_DIR, "pre-flight-done"), { force: true }); } catch {}
`;

const PRE_FLIGHT_GATE_SCRIPT = `#!/usr/bin/env node
// Generated by clarte - do not edit
import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

if (process.env.CLARTE_HOOKS_DISABLED) process.exit(0);

${PARSE_STDIN}
const tool = input.tool_name;
if (!tool) process.exit(0);

const GATED_TOOLS = new Set(["Read", "Grep", "Glob"]);
const FILE_READ_BASH = /\\b(cat|head|tail)\\s+\\S*\\.(?:ts|js|tsx|jsx|mjs|cjs|py|rs|go|java|rb|c|cpp|h|md)\\b/;

const isGated = GATED_TOOLS.has(tool) ||
  (tool === "Bash" && FILE_READ_BASH.test(input.tool_input?.command || ""));
if (!isGated) process.exit(0);

const cwd = input.cwd || process.cwd();
const TASK_CONTEXT = resolve(cwd, ".clarte/task-context.md");
const DONE_MARKER = resolve(cwd, "${PRE_FLIGHT_DONE}");

// Only gate when task-context.md exists (routing data is available)
if (!existsSync(TASK_CONTEXT)) process.exit(0);
// Gate already passed
if (existsSync(DONE_MARKER)) process.exit(0);

const output = JSON.stringify({
  hookSpecificOutput: {
    hookEventName: "PreToolUse",
    permissionDecision: "deny",
    permissionDecisionReason: "Pre-flight gate: spawn the clarte-pre-flight agent before reading any files.\\nCall: Agent(subagent_type=\\"clarte-pre-flight\\", prompt=\\"<task description>\\")\\nIt reads the relevant files and returns exact edit instructions. Apply them directly - no further reads needed.",
  }
});
process.stdout.write(output);
`;

const FAIL_FAST_SCRIPT = `#!/usr/bin/env node
// Generated by clarte - do not edit
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve } from "node:path";

if (process.env.CLARTE_HOOKS_DISABLED) process.exit(0);

${PARSE_STDIN}
const tool = input.tool_name;
if (!tool) process.exit(0);

const cwd = input.cwd || process.cwd();
const STATE_DIR = resolve(cwd, ".clarte/hooks/.state");
const FF_STATE = STATE_DIR + "/fail-fast.json";
const THRESHOLD = 3;
const TEST_RE = /\\b(npm\\s+test|npm\\s+run\\s+test|pnpm\\s+(run\\s+)?test|yarn\\s+test|bun\\s+(run\\s+)?test|npx\\s+(vitest|jest|mocha)|vitest|jest|mocha|pytest|cargo\\s+test|go\\s+test)\\b/;
const debug = process.env.CLARTE_HOOK_DEBUG === "1";

function log(msg) { if (debug) process.stderr.write("[fail-fast] " + msg + "\\n"); }

function readFFState() {
  try { return JSON.parse(readFileSync(FF_STATE, "utf-8")); } catch { return { base: "", count: 0 }; }
}

function writeFFState(state) {
  try { mkdirSync(STATE_DIR, { recursive: true }); writeFileSync(FF_STATE, JSON.stringify(state)); } catch {}
}

function extractBase(cmd) {
  return cmd.split("|")[0].replace(/\\s*2>&1\\s*$/, "").trim();
}

if (tool !== "Bash" && tool !== "Edit" && tool !== "Write") process.exit(0);

if (existsSync(resolve(cwd, ".clarte/fail-fast-override"))) {
  log("override file found, skipping");
  process.exit(0);
}

if (tool === "Edit" || tool === "Write") {
  log("edit/write detected, resetting state");
  writeFFState({ base: "", count: 0 });
  process.exit(0);
}

if (tool === "Bash") {
  const cmd = input.tool_input?.command || "";
  if (TEST_RE.test(cmd)) {
    const base = extractBase(cmd);
    const state = readFFState();
    if (state.base === base) {
      state.count += 1;
    } else {
      state.base = base;
      state.count = 1;
    }
    log("test #" + state.count + " base: " + base.slice(0, 80));
    writeFFState(state);
    if (state.count >= THRESHOLD) {
      const output = JSON.stringify({
        hookSpecificOutput: {
          hookEventName: "PreToolUse",
          permissionDecision: "deny",
          permissionDecisionReason: "Blocked: you have run the same test command " + state.count + " times with no code edits in between. The test output will not change. Re-read the existing output and try a different fix, or create .clarte/fail-fast-override to disable this check."
        }
      });
      process.stdout.write(output);
      process.exit(0);
    }
  }
  // Non-test Bash (grep, cat, git) does NOT reset the counter.
  // Only Edit/Write resets, because the agent actually tried a fix.
}
`;

const PRE_AGENT_SCRIPT = `#!/usr/bin/env node
// Generated by clarte - do not edit
// Fires on PreToolUse(Agent): enforces clarte-pre-flight before any other subagent.
// When the gate is armed (task-context.md exists, pre-flight-done absent):
//   - clarte-pre-flight call -> writes marker, allows
//   - any other Agent call  -> deny with redirect message
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve } from "node:path";

if (process.env.CLARTE_HOOKS_DISABLED) process.exit(0);

${PARSE_STDIN}
const cwd = input.cwd || process.cwd();
const TASK_CONTEXT = resolve(cwd, ".clarte/task-context.md");
const DONE_MARKER = resolve(cwd, ".clarte/hooks/.state/pre-flight-done");

// Only enforce when gate is armed
if (!existsSync(TASK_CONTEXT)) process.exit(0);
if (existsSync(DONE_MARKER)) process.exit(0);

const subagentType = input.tool_input?.subagent_type || "";
if (subagentType === "clarte-pre-flight") {
  // This IS the pre-flight agent - write marker before it starts
  try {
    mkdirSync(resolve(cwd, ".clarte/hooks/.state"), { recursive: true });
    writeFileSync(DONE_MARKER, new Date().toISOString());
  } catch {}
  process.exit(0);
}

// Any other subagent - deny until pre-flight has run
const output = JSON.stringify({
  hookSpecificOutput: {
    hookEventName: "PreToolUse",
    permissionDecision: "deny",
    permissionDecisionReason: "Pre-flight gate: spawn clarte-pre-flight before any exploration.\\nCall: Agent(subagent_type=\\"clarte-pre-flight\\", prompt=\\"<task description>\\")\\nIt reads the relevant files and returns exact edit instructions. Apply them directly - no further reads needed.",
  }
});
process.stdout.write(output);
`;

interface HookDef {
  event: string;
  file: string;
  matcher?: string;
  script: string;
}

const PROMPT_SCRIPT = `#!/usr/bin/env node
// Generated by clarte - do not edit
import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from "node:fs";
import { execSync } from "node:child_process";
import { resolve } from "node:path";

if (process.env.CLARTE_HOOKS_DISABLED) process.exit(0);

${PARSE_STDIN}
const prompt = input.prompt;
if (!prompt || prompt.length < 10) process.exit(0);

const trimmed = prompt.trim().toLowerCase();
const TRIVIAL = new Set(["yes", "no", "ok", "okay", "sure", "continue", "looks good", "lgtm", "go ahead", "proceed"]);
if (TRIVIAL.has(trimmed)) process.exit(0);

const root = process.cwd();

// New task: reset the pre-flight gate so the diagnostic agent runs again
try { rmSync(resolve(root, "${PRE_FLIGHT_DONE}"), { force: true }); } catch {}

// ── Primary: BM25F graph-based target resolution ──────────────────────────────
// Uses persisted import graph + AST symbol names. Falls through to git history if no graph.
const graphPath = resolve(root, ".clarte/graph.json");
if (existsSync(graphPath)) {
  let graph;
  try { graph = JSON.parse(readFileSync(graphPath, "utf-8")); } catch {}
  if (graph) {
    // Stop words: common words that match too many files and add no retrieval signal.
    // Verbs that are also discriminative function-name stems (parse, read, write) are
    // left to IDF rather than hard-stopped.
    const STOP = new Set([
      "a","an","the","in","on","at","to","for","of","and","or","is","it","be","are","was","has",
      "have","do","does","did","will","can","if","so","no","as","by","fix","bug","add","update",
      "change","make","set","get","use","run","call","join","split","that","this","with","from",
      "not","but","should","when","what","how","why","like","also","only","each","more","some",
      "just","into","true","false","null","type","values","value","default","string","strings",
      "array","arrays","number","object","function","class","file","files","test","tests",
      "column","columns","options","config","index","generated","stored","against","individual",
      "quoted","numeric","serialized","deserialized","validated","validates","generation","three","bugs",
    ]);
    const TEST_RE = /(?:^|\\/)(?:test|spec|__tests__|__mocks__)\\/|\\.(?:test|spec)\\.[jt]sx?$/;
    const K1 = 1.2, B = 0.75, PW = 1.5, SW = 1.0, EF = 0.3, CF = 0.4, MC = 0.5;

    function splitCC(s) { return s.replace(/([a-z])([A-Z])/g, "$1 $2").split(" ").filter(Boolean); }
    function tokId(id) {
      return id.split(/[^a-zA-Z0-9]+/).flatMap(p => splitCC(p)).map(t => t.toLowerCase()).filter(t => t.length >= 2 && !STOP.has(t));
    }
    function tokQ(q) { return [...new Set(tokId(q))]; }

    function resolveTargets(q, g) {
      const terms = tokQ(q);
      if (!terms.length) return [];
      const fps = Object.keys(g.files || {}).filter(fp => !TEST_RE.test(fp));
      if (!fps.length) return [];

      // Collect exported symbol names per file from import edges
      const exported = new Map();
      for (const e of (g.edges || [])) {
        if (!exported.has(e.to)) exported.set(e.to, []);
        exported.get(e.to).push(...(e.importedNames || []));
      }

      // Build BM25F documents: path field + symbols field (deduped)
      const docs = new Map();
      for (const fp of fps) {
        const syms = [...new Set([...(exported.get(fp) || []), ...((g.files[fp] && g.files[fp].symbolNames) || [])])];
        const pt = fp.split(/[/.]+/).flatMap(s => tokId(s));
        const st = syms.flatMap(n => tokId(n));
        const ptf = new Map(), stf = new Map();
        for (const t of pt) ptf.set(t, (ptf.get(t) || 0) + 1);
        for (const t of st) stf.set(t, (stf.get(t) || 0) + 1);
        docs.set(fp, { pt, st, ptf, stf, all: new Set([...ptf.keys(), ...stf.keys()]) });
      }

      // Per-field avgdl for BM25F normalization
      const N = docs.size;
      const aPL = Math.max(1, [...docs.values()].reduce((s, d) => s + d.pt.length, 0) / N);
      const sdocs = [...docs.values()].filter(d => d.st.length > 0);
      const aSL = sdocs.length ? Math.max(5, sdocs.reduce((s, d) => s + d.st.length, 0) / sdocs.length) : 5;

      // Unified IDF: term counts once per document regardless of which field it appears in
      const df = new Map();
      for (const doc of docs.values()) for (const t of doc.all) df.set(t, (df.get(t) || 0) + 1);

      const scores = new Map();
      for (const [fp, doc] of docs) {
        let sc = 0;
        for (const term of terms) {
          const dfc = df.get(term) || 1;
          const idf = Math.log((N - dfc + 0.5) / (dfc + 0.5) + 1);
          const tfP = doc.ptf.get(term) || 0, tfS = doc.stf.get(term) || 0;
          let fs = 0;
          if (tfP > 0) { const n = tfP + K1 * (1 - B + B * doc.pt.length / aPL); fs += PW * tfP * (K1 + 1) / n; }
          if (tfS > 0) { const n = tfS + K1 * (1 - B + B * doc.st.length / aSL); fs += SW * tfS * (K1 + 1) / n; }
          sc += idf * fs;
        }
        if (sc > 0) scores.set(fp, sc);
      }
      if (!scores.size) return [];

      // 1-hop import neighbor expansion
      const direct = new Set(scores.keys());
      const nbrs = new Map();
      for (const e of (g.edges || [])) {
        if (!nbrs.has(e.from)) nbrs.set(e.from, []);
        if (!nbrs.has(e.to)) nbrs.set(e.to, []);
        nbrs.get(e.from).push(e.to);
        nbrs.get(e.to).push(e.from);
      }
      for (const [f, sc] of scores) {
        if (!direct.has(f)) continue;
        const ex = sc * EF;
        for (const nb of (nbrs.get(f) || [])) if (ex > (scores.get(nb) || 0)) scores.set(nb, ex);
      }

      // Co-change coupling
      for (const c of (g.changeCoupling || [])) {
        if (c.confidence < MC) continue;
        if (direct.has(c.fileA) && !scores.has(c.fileB) && g.files[c.fileB]) scores.set(c.fileB, (scores.get(c.fileA) || 1) * CF);
        if (direct.has(c.fileB) && !scores.has(c.fileA) && g.files[c.fileA]) scores.set(c.fileA, (scores.get(c.fileB) || 1) * CF);
      }

      return [...scores.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])).slice(0, 5).map(([fp]) => fp);
    }

    const targets = resolveTargets(prompt, graph);
    if (targets.length > 0) {
      const lines = [
        "# Edit targets (clarte)", "",
        "Based on dependency graph analysis, these files are most likely to need editing.",
        "Key symbols are listed so you can navigate directly without a broad search.", "",
      ];
      for (const fp of targets) {
        lines.push("## " + fp);
        const syms = ((graph.files[fp] && graph.files[fp].symbolNames) || []).slice(0, 8);
        if (syms.length) lines.push("Key symbols: " + syms.join(", "));
        lines.push("");
      }
      try {
        mkdirSync(resolve(root, ".clarte"), { recursive: true });
        writeFileSync(resolve(root, ".clarte/task-context.md"), lines.join("\\n"));
      } catch {}
      process.exit(0);
    }
  }
}

// ── Fallback: git commit history BM25 ────────────────────────────────────────
// When no graph is available, find the most similar past commit by prompt similarity
// and surface the files it touched as candidates.
function tokenize(text) {
  return text.toLowerCase().split(/[^a-z0-9]+/).filter(t => t.length >= 3);
}

const K1 = 1.5, B = 0.75;
let logOutput;
try {
  logOutput = execSync("git log --format=%H|%s --max-count=500", {
    cwd: root, encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"],
  });
} catch { process.exit(0); }

const commits = logOutput.trim().split("\\n").filter(Boolean).map(line => {
  const sep = line.indexOf("|");
  return sep === -1 ? null : { sha: line.slice(0, sep), message: line.slice(sep + 1) };
}).filter(Boolean);

if (commits.length === 0) process.exit(0);

const docs = commits.map(c => tokenize(c.message));
const avgdl = docs.reduce((s, d) => s + d.length, 0) / docs.length || 1;
const df = new Map();
for (const doc of docs) for (const t of new Set(doc)) df.set(t, (df.get(t) ?? 0) + 1);

const query = tokenize(prompt);
const N = docs.length;

let bestScore = 0, bestCommit = null;
commits.forEach((c, i) => {
  const doc = docs[i], dl = doc.length;
  const tf = new Map();
  for (const t of doc) tf.set(t, (tf.get(t) ?? 0) + 1);
  let score = 0;
  for (const term of query) {
    const f = tf.get(term) ?? 0;
    if (!f) continue;
    const dfv = df.get(term) ?? 0;
    const idf = Math.log((N - dfv + 0.5) / (dfv + 0.5) + 1);
    score += idf * (f * (K1 + 1)) / (f + K1 * (1 - B + B * dl / avgdl));
  }
  if (score > bestScore) { bestScore = score; bestCommit = c; }
});

if (!bestCommit || bestScore === 0) process.exit(0);

let diffOutput;
try {
  diffOutput = execSync("git diff-tree --no-commit-id -r --name-only " + bestCommit.sha, {
    cwd: root, encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"],
  });
} catch { process.exit(0); }

const files = diffOutput.trim().split("\\n").filter(Boolean).filter(f => {
  const parts = f.split("/");
  const isTest = parts.some(p => p === "test" || p === "tests" || p === "spec" || p === "__tests__" || p === "fixtures");
  return !isTest && existsSync(resolve(root, f));
});

if (files.length === 0) process.exit(0);

const fileList = files.slice(0, 5).map(f => "- " + f).join("\\n");
const content = "# Edit targets (clarte)\\n\\nBased on past fixes to similar issues, these files are most likely to need editing:\\n\\n" + fileList + "\\n\\nMatched commit: " + bestCommit.message + "\\n";

try {
  mkdirSync(resolve(root, ".clarte"), { recursive: true });
  writeFileSync(resolve(root, ".clarte/task-context.md"), content);
} catch {}
`;

const HOOK_DEFS: HookDef[] = [
  { event: "SessionStart",    file: "on-session-start.mjs",    script: SESSION_START_SCRIPT },
  { event: "PreToolUse",      file: "on-pre-flight-gate.mjs",  matcher: "Read|Grep|Glob|Bash", script: PRE_FLIGHT_GATE_SCRIPT },
  { event: "PreToolUse",      file: "on-fail-fast.mjs",        script: FAIL_FAST_SCRIPT },
  { event: "PreToolUse",      file: "on-pre-agent.mjs",        matcher: "Agent", script: PRE_AGENT_SCRIPT },
  { event: "UserPromptSubmit", file: "on-prompt.mjs",          script: PROMPT_SCRIPT },
];

// Legacy events that may have had clarte hooks in previous versions - always clean these up
const ALL_HOOK_EVENTS = ["SessionStart", "PreToolUse", "PostToolUse", "UserPromptSubmit"];

const PRE_FLIGHT_AGENT_CONTENT = `---
name: clarte-pre-flight
description: Pre-flight diagnostic agent. Reads files listed in .clarte/task-context.md and returns exact edit instructions for the current task. Spawn before any file exploration.
model: haiku
---

You are a pre-flight diagnostic agent. Your job is to read the relevant source files and return complete, correct edit instructions that cover every aspect of the task.

## Steps

1. Read \`.clarte/task-context.md\` - contains the task description and the files most likely to need editing.
2. Read each listed source file in full.
3. If test files are listed, read them - your edits must make those tests pass.
4. List every distinct problem the task describes. There may be more than one.
5. For each problem, identify the exact code change needed.
6. Before returning, verify your edits collectively address ALL problems you listed. If any are missing, add them or mark them UNCERTAIN.

## Output format

Return ONLY this structure for each change. No preamble, no summary.

\`\`\`
FILE: <relative path>
LINE: <line number>
CURRENT:
<exact current code, 1-5 lines>
REPLACE:
<exact replacement code>
REASON: <one sentence>
\`\`\`

Repeat for each change. Omit files that need no changes. If you cannot determine the exact change, write \`UNCERTAIN: <file> - <reason>\` and do not guess.
`;

/**
 * Generate hook files: context-map.json and all hook scripts.
 * When enriched=true, includes extra context (instability, layers, tight coupling).
 * Pass directives for per-file directive injection.
 */
export async function generateHookFiles(
  rootDir: string,
  graph: PersistedGraph,
  enriched?: boolean,
  directives?: string[],
): Promise<void> {
  const contextMap = buildContextMap(graph, enriched, directives);

  const hooksDir = path.join(rootDir, HOOKS_DIR);
  await writeFileSafe(path.join(hooksDir, CONTEXT_MAP_FILE), JSON.stringify(contextMap, null, 2));
  for (const def of HOOK_DEFS) {
    await writeFileSafe(path.join(hooksDir, def.file), def.script);
  }
}

/**
 * Generate the pre-flight diagnostic agent file at .claude/agents/clarte-pre-flight.md.
 */
export async function generatePreFlightAgentFile(_rootDir: string): Promise<void> {
  // Must be in ~/.claude/agents/ (user-global) for subagent_type to be recognized.
  // Project-level .claude/agents/ is not loaded as a subagent_type source by Claude Code.
  const userAgentsDir = path.join(os.homedir(), ".claude", "agents");
  await writeFileSafe(path.join(userAgentsDir, "clarte-pre-flight.md"), PRE_FLIGHT_AGENT_CONTENT);
}

interface HookEntry {
  type: string;
  command: string;
}

interface MatchedHookGroup {
  matcher?: string;
  hooks: HookEntry[];
}

interface ClaudeSettings {
  hooks?: {
    PreToolUse?: MatchedHookGroup[];
    SessionStart?: MatchedHookGroup[];
    [key: string]: unknown;
  };
  [key: string]: unknown;
}

function isClartHook(entry: MatchedHookGroup): boolean {
  return entry.hooks?.some((h) => h.command?.includes(`${HOOKS_DIR}/`)) ?? false;
}

function upsertHookEntry(entries: MatchedHookGroup[], newEntry: MatchedHookGroup, hookFile: string): void {
  const existingIdx = entries.findIndex((entry) =>
    entry.hooks?.some((h) => h.command?.endsWith(`${HOOKS_DIR}/${hookFile}`)),
  );
  if (existingIdx >= 0) {
    entries[existingIdx] = newEntry;
  } else {
    entries.push(newEntry);
  }
}

/**
 * Configure Claude Code hook settings in .claude/settings.json.
 * Merges SessionStart and PreToolUse hooks without clobbering user-defined hooks.
 */
export async function configureClaudeHooks(rootDir: string): Promise<void> {
  const settingsPath = path.join(rootDir, SETTINGS_PATH);
  const raw = (await readJsonFile(settingsPath)) as ClaudeSettings | null;
  const settings: ClaudeSettings = raw ?? {};

  if (!settings.hooks) {
    settings.hooks = {};
  }

  // Clean up all existing clarte hooks across all known events (including legacy PostToolUse).
  for (const event of ALL_HOOK_EVENTS) {
    const group = settings.hooks[event] as MatchedHookGroup[] | undefined;
    if (group) {
      settings.hooks[event] = group.filter((entry) => !isClartHook(entry));
    }
  }

  // Insert fresh hooks
  for (const def of HOOK_DEFS) {
    const group = (settings.hooks[def.event] ??= []) as MatchedHookGroup[];
    const entry: MatchedHookGroup = {
      ...(def.matcher ? { matcher: def.matcher } : {}),
      hooks: [{ type: "command", command: `node ${HOOKS_DIR}/${def.file}` }],
    };
    upsertHookEntry(group, entry, def.file);
  }

  await writeFileSafe(settingsPath, JSON.stringify(settings, null, 2) + "\n");
}
