import type {
  ContextAnalysis,
  DetectedContext,
  HubFile,
  ImportGraph,
  NeighborhoodResult,
  SnapshotEntry,
} from "../types.js";
import { buildDirectives } from "../templates/directives.js";

export interface DiffRenderContext {
  changedFiles: string[];
  ref?: string;
  diffStat: Map<string, { added: number; removed: number }> | null;
  hubFileMap: Map<string, HubFile>;
  graph: ImportGraph;
  neighborhood: NeighborhoodResult;
  testFiles: Set<string>;
  entryIndex: Map<string, SnapshotEntry[]>;
  relevantCycles: Array<{ chain: string[]; breakHint?: string }>;
  gitActivity: ContextAnalysis["gitActivity"];
  detected: DetectedContext;
  analysis: ContextAnalysis;
}

/**
 * Render the diff context markdown from pre-computed analysis data.
 */
export function renderDiffContext(ctx: DiffRenderContext): string {
  const {
    changedFiles,
    ref,
    diffStat,
    hubFileMap,
    graph,
    neighborhood,
    testFiles,
    entryIndex,
    relevantCycles,
    gitActivity,
    detected,
    analysis,
  } = ctx;

  const changedSet = new Set(changedFiles);
  const { hop1: hop1Set, hop2: hop2Set } = neighborhood;
  const neighborSet = new Set([...hop1Set, ...hop2Set]);
  const sections: string[] = [];
  const isSingleFile = changedFiles.length === 1;

  if (isSingleFile) {
    renderSingleFileHeader(sections, changedFiles[0], hubFileMap, graph, diffStat, ref);
  } else {
    renderMultiFileHeader(sections, changedFiles, hubFileMap, graph, diffStat, ref);
  }

  renderTemporalCoupling(sections, changedFiles, changedSet, gitActivity);
  renderCircularDeps(sections, relevantCycles);
  renderNeighbors(sections, neighborhood, hubFileMap, graph);
  renderRelatedTests(sections, testFiles);
  renderSignatures(sections, changedSet, neighborSet, entryIndex, graph, detected.language);
  renderScopedDirectives(sections, changedFiles, analysis, detected);

  if (isSingleFile && hop1Set.size === 0 && testFiles.size === 0) {
    const filesWithEntries = [...changedSet, ...neighborSet].filter((f) => entryIndex.has(f));
    if (filesWithEntries.length === 0) {
      sections.push("> This file is not in the import graph. Run `--diff` without file arguments to see all changes.");
      sections.push("");
    }
  }

  return sections.join("\n");
}

function renderSingleFileHeader(
  sections: string[],
  file: string,
  hubFileMap: Map<string, HubFile>,
  graph: ImportGraph,
  diffStat: Map<string, { added: number; removed: number }> | null,
  ref?: string,
): void {
  const hub = hubFileMap.get(file);
  const importedBy = graph.inDegree.get(file) ?? 0;
  const role = hub?.role ?? "Leaf";
  const stat = diffStat?.get(file);
  const statStr = stat ? `, +${stat.added} / -${stat.removed}` : "";
  sections.push("# Diff Context");
  sections.push("");
  sections.push(
    `> \`${file}\` (${role}, imported by ${importedBy}${statStr})${ref ? ` vs \`${ref}\`` : ""}. Generated by Clart\u00e9.`,
  );
  sections.push("");

  if (hub && (hub.role === "Foundation" || hub.role === "Orchestrator" || hub.role === "Bridge")) {
    sections.push(
      `**Risk:** ${hub.role} file, imported by ${hub.importedBy} file${hub.importedBy === 1 ? "" : "s"}. Check dependents for breaking changes.`,
    );
    sections.push("");
  }
}

function renderMultiFileHeader(
  sections: string[],
  changedFiles: string[],
  hubFileMap: Map<string, HubFile>,
  graph: ImportGraph,
  diffStat: Map<string, { added: number; removed: number }> | null,
  ref?: string,
): void {
  sections.push("# Diff Context");
  sections.push("");
  sections.push(
    `> Focused context for ${changedFiles.length} changed files${ref ? ` vs \`${ref}\`` : ""}. Generated by Clart\u00e9.`,
  );
  sections.push("");

  sections.push("## Changed Files");
  sections.push("");
  if (diffStat && diffStat.size > 0) {
    sections.push("| File | Role | Imported By | Lines (+/-) |");
    sections.push("|------|------|-------------|-------------|");
    for (const f of changedFiles) {
      const hub = hubFileMap.get(f);
      const importedBy = graph.inDegree.get(f) ?? 0;
      const role = hub?.role ?? "Leaf";
      const stat = diffStat.get(f);
      const statStr = stat ? `+${stat.added} / -${stat.removed}` : "";
      sections.push(`| \`${f}\` | ${role} | ${importedBy} | ${statStr} |`);
    }
  } else {
    sections.push("| File | Role | Imported By |");
    sections.push("|------|------|-------------|");
    for (const f of changedFiles) {
      const hub = hubFileMap.get(f);
      const importedBy = graph.inDegree.get(f) ?? 0;
      const role = hub?.role ?? "Leaf";
      sections.push(`| \`${f}\` | ${role} | ${importedBy} |`);
    }
  }
  sections.push("");

  const riskNotes: string[] = [];
  for (const f of changedFiles) {
    const hub = hubFileMap.get(f);
    if (hub && (hub.role === "Foundation" || hub.role === "Orchestrator" || hub.role === "Bridge")) {
      riskNotes.push(
        `\`${f}\` is a ${hub.role} file, imported by ${hub.importedBy} file${hub.importedBy === 1 ? "" : "s"}. Check dependents for breaking changes.`,
      );
    }
  }
  if (riskNotes.length > 0) {
    sections.push("### Risk Annotations");
    sections.push("");
    for (const note of riskNotes) {
      sections.push(`- ${note}`);
    }
    sections.push("");
  }
}

function renderTemporalCoupling(
  sections: string[],
  changedFiles: string[],
  changedSet: Set<string>,
  gitActivity: ContextAnalysis["gitActivity"],
): void {
  if (!gitActivity?.changeCoupling) return;
  const suggestions: string[] = [];
  for (const f of changedFiles) {
    const DIFF_COUPLING_THRESHOLD = 0.5;
    const partners = gitActivity.changeCoupling
      .filter(
        (c) =>
          c.confidence >= DIFF_COUPLING_THRESHOLD &&
          ((c.fileA === f && !changedSet.has(c.fileB)) || (c.fileB === f && !changedSet.has(c.fileA))),
      )
      .map((c) => {
        const partner = c.fileA === f ? c.fileB : c.fileA;
        const pct = Math.round(c.confidence * 100);
        return `\`${partner}\` (${pct}% co-change)`;
      });
    if (partners.length > 0) {
      suggestions.push(`When modifying \`${f}\`, consider also checking: ${partners.join(", ")}`);
    }
  }
  if (suggestions.length > 0) {
    sections.push("### Temporal Coupling");
    sections.push("");
    sections.push("> Files that frequently change together but are not in this diff.");
    sections.push("");
    for (const s of suggestions) {
      sections.push(`- ${s}`);
    }
    sections.push("");
  }
}

function renderCircularDeps(sections: string[], relevantCycles: Array<{ chain: string[]; breakHint?: string }>): void {
  const cycleNotes: string[] = [];
  for (const dep of relevantCycles) {
    const chainStr = dep.chain.map((f) => `\`${f}\``).join(" -> ");
    if (dep.breakHint) {
      cycleNotes.push(`Cycle: ${chainStr}. ${dep.breakHint}`);
    } else {
      cycleNotes.push(`Cycle: ${chainStr}. Consider breaking this circular dependency.`);
    }
  }
  if (cycleNotes.length > 0) {
    sections.push("### Circular Dependencies");
    sections.push("");
    sections.push("> Changed files participate in these cycles.");
    sections.push("");
    for (const note of cycleNotes) {
      sections.push(`- ${note}`);
    }
    sections.push("");
  }
}

function renderNeighbors(
  sections: string[],
  neighborhood: NeighborhoodResult,
  hubFileMap: Map<string, HubFile>,
  graph: ImportGraph,
): void {
  const { hop1: hop1Set, hop2: hop2Set } = neighborhood;
  if (hop1Set.size === 0 && hop2Set.size === 0) return;

  sections.push("## Neighbors");
  sections.push("");

  const renderNeighborTable = (files: Set<string>, cap?: number) => {
    const sorted = [...files].sort();
    const capped = cap ? sorted.slice(0, cap) : sorted;
    sections.push("| File | Role | Imported By |");
    sections.push("|------|------|-------------|");
    for (const f of capped) {
      const hub = hubFileMap.get(f);
      const importedBy = graph.inDegree.get(f) ?? 0;
      const role = hub?.role ?? "Leaf";
      sections.push(`| \`${f}\` | ${role} | ${importedBy} |`);
    }
    sections.push("");
  };

  if (neighborhood.hop1Importers.size > 0) {
    sections.push("### Dependents (import changed files)");
    sections.push("");
    renderNeighborTable(neighborhood.hop1Importers);
  }

  if (neighborhood.hop1Dependencies.size > 0) {
    sections.push("### Dependencies (imported by changed files)");
    sections.push("");
    renderNeighborTable(neighborhood.hop1Dependencies);
  }

  if (hop2Set.size > 0) {
    sections.push("### Indirect (2-hop)");
    sections.push("");
    renderNeighborTable(hop2Set, 15);
  }
}

function renderRelatedTests(sections: string[], testFiles: Set<string>): void {
  if (testFiles.size === 0) return;
  sections.push("## Related Tests");
  sections.push("");
  sections.push("> Run these tests after your changes.");
  sections.push("");
  for (const f of [...testFiles].sort()) {
    sections.push(`- \`${f}\``);
  }
  sections.push("");
}

const LANG_FENCE: Record<string, string> = {
  typescript: "ts",
  javascript: "js",
  python: "py",
  go: "go",
  rust: "rs",
  java: "java",
};

function renderSignatures(
  sections: string[],
  changedSet: Set<string>,
  neighborSet: Set<string>,
  entryIndex: Map<string, SnapshotEntry[]>,
  graph: ImportGraph,
  language: string,
): void {
  const filesWithEntries = [...changedSet, ...neighborSet]
    .filter((f) => entryIndex.has(f))
    .sort((a, b) => (graph.centrality.get(b) ?? 0) - (graph.centrality.get(a) ?? 0));

  if (filesWithEntries.length === 0) return;

  sections.push("## Signatures in Scope");
  sections.push("");
  sections.push("Key type signatures and function declarations from changed and neighbor files.");
  sections.push("");
  sections.push(`\`\`\`${LANG_FENCE[language] ?? "ts"}`);
  for (const f of filesWithEntries.slice(0, 20)) {
    const entries = entryIndex.get(f) ?? [];
    if (entries.length === 0) continue;
    sections.push(`// ${f}`);
    for (const e of entries.slice(0, 5)) {
      sections.push(e.signature);
      sections.push("");
    }
  }
  sections.push("```");
  sections.push("");
}

function renderScopedDirectives(
  sections: string[],
  changedFiles: string[],
  analysis: ContextAnalysis,
  detected: DetectedContext,
): void {
  const allDirectives = buildDirectives(analysis, detected);
  const scopedDirectives = allDirectives.filter((d) => changedFiles.some((f) => d.includes(f)));
  if (scopedDirectives.length === 0) return;

  sections.push("## Working Guidelines");
  sections.push("");
  sections.push("> Scoped directives for changed files.");
  sections.push("");
  for (const d of scopedDirectives) {
    sections.push(`- ${d}`);
  }
  sections.push("");
}
