import { describe, expect, it, vi, beforeEach } from "vitest";

vi.mock("../utils.js", async () => {
  const actual = await vi.importActual<typeof import("../utils.js")>("../utils.js");
  return {
    ...actual,
    readFileOr: vi.fn(),
  };
});

vi.mock("tinyglobby", () => ({
  glob: vi.fn(),
}));

vi.mock("../graph.js", async () => {
  const actual = await vi.importActual<typeof import("../graph.js")>("../graph.js");
  return {
    ...actual,
    findUsedExports: () => new Set<string>(),
  };
});

import { generateSnapshot } from "../snapshot/snapshot.js";
import { readFileOr } from "../utils.js";
import { glob } from "tinyglobby";
import type { DetectedContext } from "../types.js";

const mockReadFileOr = vi.mocked(readFileOr);
const mockGlob = vi.mocked(glob);

function makeGoCtx(overrides?: Partial<DetectedContext>): DetectedContext {
  return {
    rootDir: "/test-project",
    language: "go",
    hasTypeScript: false,
    packageManager: "go",
    linter: "gofmt",
    frameworks: [],
    directories: ["cmd", "internal"],
    dependencies: [],
    isGitRepo: true,
    totalSourceBytes: 5000,
    sourceFileCount: 10,
    monorepo: null,
    ...overrides,
  };
}

beforeEach(() => {
  vi.clearAllMocks();
});

describe("Go snapshot extraction", () => {
  it("extracts an exported struct", async () => {
    const goContent = `package models

type User struct {
	ID    int64
	Name  string
	Email string
}
`;

    mockGlob.mockResolvedValue(["models/user.go"] as any);
    mockReadFileOr.mockResolvedValue(goContent);

    const result = await generateSnapshot(makeGoCtx(), []);

    expect(result.entries.length).toBe(1);
    expect(result.entries[0].category).toBe("type");
    expect(result.entries[0].signature).toContain("type User struct {");
    expect(result.entries[0].signature).toContain("Name  string");
  });

  it("extracts an exported interface", async () => {
    const goContent = `package services

type UserService interface {
	GetUser(id int64) (*User, error)
	CreateUser(name string) (*User, error)
}
`;

    mockGlob.mockResolvedValue(["services/user.go"] as any);
    mockReadFileOr.mockResolvedValue(goContent);

    const result = await generateSnapshot(makeGoCtx(), []);

    expect(result.entries.length).toBe(1);
    expect(result.entries[0].category).toBe("interface");
    expect(result.entries[0].signature).toContain("type UserService interface {");
  });

  it("extracts exported functions", async () => {
    const goContent = `package handlers

func HandleRequest(w http.ResponseWriter, r *http.Request) {
	// handler body
}

func ProcessOrder(orderID int64) error {
	return nil
}
`;

    mockGlob.mockResolvedValue(["handlers/main.go"] as any);
    mockReadFileOr.mockResolvedValue(goContent);

    const result = await generateSnapshot(makeGoCtx(), []);

    expect(result.entries.length).toBe(2);
    const sigs = result.entries.map((e) => e.signature);
    expect(result.entries.every((e) => e.category === "function")).toBe(true);
    expect(sigs.some((s) => s.includes("func HandleRequest(w http.ResponseWriter, r *http.Request)"))).toBe(true);
    expect(sigs.some((s) => s.includes("func ProcessOrder(orderID int64) error"))).toBe(true);
  });

  it("extracts exported methods with receivers", async () => {
    const goContent = `package models

func (u *User) FullName() string {
	return u.FirstName + " " + u.LastName
}

func (u *User) Validate() error {
	return nil
}
`;

    mockGlob.mockResolvedValue(["models/user.go"] as any);
    mockReadFileOr.mockResolvedValue(goContent);

    const result = await generateSnapshot(makeGoCtx(), []);

    expect(result.entries.length).toBe(2);
    expect(result.entries[0].category).toBe("function");
    expect(result.entries[0].signature).toContain("(User).FullName() string");
    expect(result.entries[1].signature).toContain("(User).Validate() error");
  });

  it("skips unexported symbols", async () => {
    const goContent = `package internal

type publicStruct struct {
	field string
}

func helperFunc() {
}

type ExportedStruct struct {
	Field string
}

func ExportedFunc() {
}
`;

    mockGlob.mockResolvedValue(["internal/core.go"] as any);
    mockReadFileOr.mockResolvedValue(goContent);

    const result = await generateSnapshot(makeGoCtx(), []);

    // Only exported symbols should be extracted
    expect(result.entries.length).toBe(2);
    const sigs = result.entries.map((e) => e.signature);
    expect(sigs.some((s) => s.includes("ExportedStruct"))).toBe(true);
    expect(sigs.some((s) => s.includes("ExportedFunc"))).toBe(true);
  });

  it("skips generated files", async () => {
    const goContent = `// Code generated by protoc-gen-go. DO NOT EDIT.
package pb

type Message struct {
	ID string
}
`;

    mockGlob.mockResolvedValue(["pb/message.go"] as any);
    mockReadFileOr.mockResolvedValue(goContent);

    const result = await generateSnapshot(makeGoCtx(), []);

    expect(result.entries.length).toBe(0);
  });

  it("extracts type aliases", async () => {
    const goContent = `package types

type UserID int64

type Callback func(string) error
`;

    mockGlob.mockResolvedValue(["types/aliases.go"] as any);
    mockReadFileOr.mockResolvedValue(goContent);

    const result = await generateSnapshot(makeGoCtx(), []);

    expect(result.entries.length).toBe(2);
    expect(result.entries[0].category).toBe("type");
    expect(result.entries[0].signature).toContain("type UserID int64");
    expect(result.entries[1].signature).toContain("type Callback func(string) error");
  });

  it("extracts const blocks with exported names (iota patterns)", async () => {
    const goContent = `package status

const (
	StatusPending  = iota
	StatusActive
	StatusInactive
)
`;

    mockGlob.mockResolvedValue(["status/status.go"] as any);
    mockReadFileOr.mockResolvedValue(goContent);

    const result = await generateSnapshot(makeGoCtx(), []);

    expect(result.entries.length).toBe(1);
    expect(result.entries[0].category).toBe("type");
    expect(result.entries[0].signature).toContain("StatusPending");
    expect(result.entries[0].signature).toContain("StatusActive");
  });

  it("renders go code blocks in markdown", async () => {
    const goContent = `package models

type User struct {
	Name string
}

func NewUser(name string) *User {
	return &User{Name: name}
}
`;

    mockGlob.mockResolvedValue(["models/user.go"] as any);
    mockReadFileOr.mockResolvedValue(goContent);

    const result = await generateSnapshot(makeGoCtx(), []);

    expect(result.markdown).toContain("```go");
    expect(result.markdown).not.toContain("```ts");
  });
});
