import path from "node:path";
import * as p from "@clack/prompts";
import { theme as t } from "../theme.js";
import type {
  CodeSnapshot,
  ContextAnalysis,
  DetectedContext,
  GeneratedFile,
  ProgressCallback,
  UserAnswers,
} from "../types.js";
import type { PersistedGraph } from "../types/persisted-graph.js";
import { fileExists, readFileOr, writeFileSafe } from "../utils.js";
import { buildMainContext, getMainContextFilename } from "../templates/main-context.js";
import { buildClaudeSkills, renderClaudeSkill } from "../templates/claude-skills.js";
import { buildPreFlightAgent } from "../templates/pre-flight-agent.js";
import { detectContext } from "../detect/detect.js";
import { generateSnapshot } from "../snapshot/snapshot.js";

export interface GenerateFilesOptions {
  ctx: DetectedContext;
  answers: UserAnswers;
  snapshot: CodeSnapshot | null;
  yes?: boolean;
  dryRun?: boolean;
  analysis?: ContextAnalysis;
  generateSkills?: boolean;
  onVerbose?: ProgressCallback;
  persistedGraph?: PersistedGraph | null;
}

/**
 * Generate all context files based on detection, user answers, and snapshot.
 * Returns the list of files that were generated.
 * When dryRun is true, no files are written to disk.
 */
export async function generateFiles(opts: GenerateFilesOptions): Promise<GeneratedFile[]> {
  const {
    ctx,
    answers,
    snapshot,
    yes = false,
    dryRun = false,
    analysis,
    generateSkills = false,
    onVerbose,
  } = opts;
  // Deduplicate files by path (e.g. multiple targets that share the same output path)
  const fileMap = new Map<string, GeneratedFile>();

  async function addFile(filePath: string, content: string) {
    if (fileMap.has(filePath)) return;
    const absPath = path.join(ctx.rootDir, filePath);
    fileMap.set(filePath, {
      path: filePath,
      content,
      existed: await fileExists(absPath),
    });
    onVerbose?.(`Prepared ${filePath} (${content.length} bytes)`);
  }

  for (const ide of answers.ides) {
    const mainFilename = getMainContextFilename(ide);
    const mainContent = await buildMainContext(ctx, answers, snapshot, analysis);
    await addFile(mainFilename, mainContent);

    // Always write agent to .clarte/agents/ (source of truth).
    // For Cursor, also copy to .cursor/agents/ (no hook mechanism to do it later).
    // For Claude, the on-prompt hook copies to .claude/agents/ on demand.
    if (ide === "claude" || ide === "cursor") {
      await addFile(".clarte/agents/clarte-pre-flight.md", buildPreFlightAgent());
      if (ide === "cursor") {
        await addFile(".cursor/agents/clarte-pre-flight.md", buildPreFlightAgent());
      }
    }

    if (generateSkills && ide === "claude") {
      const skills = buildClaudeSkills();
      for (const skill of skills) {
        const skillPath = `.claude/skills/${skill.name}/SKILL.md`;
        const skillContent = renderClaudeSkill(skill);
        await addFile(skillPath, skillContent);
      }
    }

    if (ide === "claude") {
      // Write a lightweight CLAUDE.md stub that redirects to the rules file,
      // halving cold-start token cost when both files would otherwise be loaded.
      // Only write if the file doesn't exist or was previously generated by us;
      // user-written CLAUDE.md files are left untouched.
      const claudeMdPath = "CLAUDE.md";
      const existingClaudeMd = await readFileOr(path.join(ctx.rootDir, claudeMdPath));
      if (!existingClaudeMd || existingClaudeMd.includes("<!-- clarte: generated")) {
        const ts = new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
        await addFile(
          claudeMdPath,
          `# Project Context\n\nSee \`.claude/rules/clarte.md\` for full architectural context.\n\nFirst action on every coding task: call Agent(subagent_type="clarte-pre-flight", prompt="<your full task>"). It reads the relevant files and returns exact edit instructions. Apply them directly - do not read files yourself before or after. Skip this step if \`.clarte/task-context.md\` does not exist.\n\n<!-- clarte: generated ${ts}. Run npx clarte to regenerate. -->\n`,
        );
      }
    }
  }

  if (answers.generatePerPackage && ctx.monorepo && ctx.monorepo.packages.length > 0) {
    for (const pkg of ctx.monorepo.packages) {
      const pkgRootDir = path.join(ctx.rootDir, pkg.path);

      // Detect context for this specific package
      const pkgCtx = await detectContext(pkgRootDir);

      // Generate snapshot scoped to this package
      let pkgSnapshot: CodeSnapshot | null = null;
      if (answers.generateSnapshot) {
        pkgSnapshot = await generateSnapshot(pkgCtx, []);
        if (pkgSnapshot.entries.length === 0) pkgSnapshot = null;
      }

      // Build scoped answers for this package
      const pkgAnswers: UserAnswers = {
        ...answers,
        projectPurpose: `${pkg.name}, part of the ${path.basename(ctx.rootDir)} monorepo. ${answers.projectPurpose}`,
        generatePerPackage: false, // don't recurse
      };

      for (const ide of answers.ides) {
        const pkgMainFilename = getMainContextFilename(ide);
        const pkgContent = await buildMainContext(pkgCtx, pkgAnswers, pkgSnapshot);
        const pkgFilePath = path.join(pkg.path, pkgMainFilename);
        await addFile(pkgFilePath, pkgContent);
      }
    }
  }

  const files = Array.from(fileMap.values());

  let preservedCount = 0;
  for (const file of files) {
    if (!file.existed) continue;
    // Skip user section preservation for rules-directory files (clarte owns these entirely)
    if (file.path.startsWith(".claude/rules/") || file.path.startsWith(".cursor/rules/")) continue;
    // Only preserve in markdown-based context files (not YAML, not skills)
    if (
      !file.path.endsWith(".md") &&
      !file.path.startsWith(".windsurfrules") &&
      !file.path.startsWith(".clinerules") &&
      !file.path.startsWith(".continuerules")
    )
      continue;

    const absPath = path.join(ctx.rootDir, file.path);
    const existingContent = await readFileOr(absPath);
    if (!existingContent) continue;

    const userSections = extractUserSections(existingContent);
    if (userSections.length > 0) {
      file.content = mergeUserSections(file.content, userSections);
      preservedCount += userSections.length;
      onVerbose?.(`Preserved ${userSections.length} user section(s) in ${file.path}`);
    }
  }

  if (preservedCount > 0) {
    p.log.info(
      t.text(
        `Preserved ${t.textBold(String(preservedCount))} custom section${preservedCount === 1 ? "" : "s"} (clarte:user markers)`,
      ),
    );
  }

  if (dryRun) {
    return files;
  }

  const existingFiles = files.filter((f) => f.existed);
  if (existingFiles.length > 0 && !yes) {
    p.log.warn(
      t.warn("The following files already exist:") +
        "\n" +
        existingFiles.map((f) => t.text(`  - ${f.path}`)).join("\n"),
    );

    const overwrite = await p.confirm({
      message: t.text("Overwrite existing files?"),
      active: t.soft("Yes"),
      inactive: t.soft("No"),
    });

    if (p.isCancel(overwrite) || !overwrite) {
      const newFiles = files.filter((f) => !f.existed);
      if (newFiles.length === 0) {
        p.log.info(t.text("No new files to write. Exiting."));
        return [];
      }
      p.log.info(t.text(`Writing ${newFiles.length} new file(s), skipping existing.`));
      for (const file of newFiles) {
        await writeFileSafe(path.join(ctx.rootDir, file.path), file.content);
      }
      return newFiles;
    }
  }

  for (const file of files) {
    await writeFileSafe(path.join(ctx.rootDir, file.path), file.content);
    onVerbose?.(`Wrote ${file.path}`);
  }

  return files;
}

const USER_START = "<!-- clarte:user-start -->";
const USER_END = "<!-- clarte:user-end -->";

interface UserSection {
  /** Full content including markers */
  content: string;
  /** The nearest preceding ## header (anchor for repositioning) */
  anchor: string | null;
}

/**
 * Extract user-preserved sections from existing file content.
 * Each section is delimited by <!-- clarte:user-start --> and <!-- clarte:user-end -->.
 */
export function extractUserSections(content: string): UserSection[] {
  const sections: UserSection[] = [];
  let searchFrom = 0;

  while (searchFrom < content.length) {
    const startIdx = content.indexOf(USER_START, searchFrom);
    if (startIdx < 0) break;

    const endIdx = content.indexOf(USER_END, startIdx + USER_START.length);
    if (endIdx < 0) break; // Unclosed marker — skip

    // Check for nested start markers (malformed user sections)
    const inner = content.slice(startIdx + USER_START.length, endIdx);
    if (inner.includes(USER_START)) {
      console.error("[clarte] Warning: nested clarte:user-start markers detected. Skipping malformed section.");
      searchFrom = endIdx + USER_END.length;
      continue;
    }

    const fullBlock = content.slice(startIdx, endIdx + USER_END.length);

    // Find nearest preceding ## header as position anchor
    const before = content.slice(0, startIdx);
    const headers = before.match(/^## .+$/gm);
    const anchor = headers ? headers[headers.length - 1] : null;

    sections.push({ content: fullBlock, anchor });
    searchFrom = endIdx + USER_END.length;
  }

  return sections;
}

/**
 * Merge preserved user sections into newly generated content.
 * Each section is re-inserted after its anchor header (nearest preceding ## header
 * from the original file). If the anchor is not found, the section is appended at the end.
 */
export function mergeUserSections(newContent: string, userSections: UserSection[]): string {
  if (userSections.length === 0) return newContent;

  let result = newContent;

  for (const section of userSections) {
    // Skip if this exact user block is somehow already in the new content
    if (result.includes(section.content)) continue;

    if (section.anchor) {
      // Find the anchor header in the new content
      const anchorIdx = result.indexOf(section.anchor);
      if (anchorIdx >= 0) {
        // Find the start of the next ## header after the anchor
        const afterAnchor = anchorIdx + section.anchor.length;
        const nextHeaderIdx = result.indexOf("\n## ", afterAnchor);

        if (nextHeaderIdx >= 0) {
          // Insert before the next header
          const before = result.slice(0, nextHeaderIdx);
          const after = result.slice(nextHeaderIdx);
          result = before.trimEnd() + "\n\n" + section.content + "\n" + after;
        } else {
          // No next header — insert before the final newline
          result = result.trimEnd() + "\n\n" + section.content + "\n";
        }
        continue;
      }
    }

    // No anchor found: append at end
    result = result.trimEnd() + "\n\n" + section.content + "\n";
  }

  return result;
}
