#!/usr/bin/env bash
set -euo pipefail

# ── Phase 0: updatedInput Mechanism Test ──────────────────────────
# Verifies that Claude Code honors the updatedInput field by:
# 1. Setting up a project with a verbose test suite and the truncate hook
# 2. Running a single claude -p session that triggers npm test
# 3. Inspecting the session log for evidence of truncation
#
# Usage:
#   ./scripts/truncate-phase0.sh
#
# NOTE: Cannot run from inside a Claude Code session (nesting blocked).
# Run this script directly from a terminal.

export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Allow nested execution by unsetting the guard variable
unset CLAUDECODE

CLARTE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BENCH_DIR="/tmp/clarte-truncate-phase0-$(date +%Y%m%d-%H%M%S)"
WORK_DIR="$BENCH_DIR/project"
RESULTS_DIR="$BENCH_DIR/results"
MAX_BUDGET="0.50"
ALLOWED_TOOLS="Read,Write,Edit,Glob,Grep,Bash"

mkdir -p "$RESULTS_DIR" "$WORK_DIR"

echo "Phase 0: updatedInput Mechanism Test"
echo "Dir: $BENCH_DIR"
echo ""

# ── Create a minimal project with a verbose test ──────────────────
cd "$WORK_DIR"
git init --quiet

cat > package.json << 'PKGJSON'
{
  "name": "truncate-phase0",
  "scripts": {
    "test": "node test.js"
  }
}
PKGJSON

# Test script that outputs 50 lines then fails (so we can verify exit code)
cat > test.js << 'TESTJS'
for (let i = 1; i <= 50; i++) {
  console.log(`  line ${i}: test output padding to simulate verbose framework output`);
}
console.log("");
console.log("  1 failing");
console.log("");
console.log("  FAIL src/foo.test.ts");
console.log("    Expected: 42");
console.log("    Received: 0");
console.log("");
console.log("Tests: 1 failed, 9 passed, 10 total");
process.exit(1);
TESTJS

cat > src.js << 'SRCJS'
// Placeholder source file with a bug
function add(a, b) {
  return a - b; // BUG: should be a + b
}
module.exports = { add };
SRCJS

cat > CLAUDE.md << 'CLAUDEMD'
# truncate-phase0
A minimal project. Tests use node test.js.
CLAUDEMD

git add -A && git commit --quiet -m "init" --no-gpg-sign

# ── Set up hooks manually (mechanism test, not clarte integration) ─
mkdir -p .clarte/hooks .claude

# Truncate hook with debug logging
cat > .clarte/hooks/on-truncate-test.mjs << 'HOOKEOF'
#!/usr/bin/env node
import { readFileSync, appendFileSync } from "node:fs";

const LOG = ".clarte/hooks/truncate-debug.log";
function log(msg) { try { appendFileSync(LOG, new Date().toISOString() + " " + msg + "\n"); } catch {} }

log("hook invoked");

let input;
try { input = JSON.parse(readFileSync(0, "utf-8")); } catch (e) { log("parse error: " + e); process.exit(0); }

log("tool_name=" + input.tool_name);
if (input.tool_name !== "Bash") { log("not Bash"); process.exit(0); }

const cmd = input.tool_input?.command || "";
log("command=" + cmd);

const TEST_RE = /\b(npm\s+test|npm\s+run\s+test|pnpm\s+(run\s+)?test|yarn\s+test|bun\s+(run\s+)?test|npx\s+(vitest|jest|mocha)|vitest|jest|mocha|pytest|cargo\s+test|go\s+test)\b/;
if (!TEST_RE.test(cmd)) { log("not test cmd"); process.exit(0); }
if (cmd.includes("|") || cmd.replace(/2>&1/g, "").includes(">")) { log("has pipe/redir"); process.exit(0); }

const clean = cmd.replace(/\s*2>&1\s*$/, "").trim();
const escaped = clean.replace(/'/g, "'\\''" );
const rewritten = "bash -c 'set -o pipefail; " + escaped + " 2>&1 | tail -20'";

log("rewritten=" + rewritten);

const output = JSON.stringify({
  hookSpecificOutput: {
    hookEventName: "PreToolUse",
    permissionDecision: "allow",
    updatedInput: { command: rewritten }
  }
});
log("output=" + output);
process.stdout.write(output);
log("done");
HOOKEOF

# Write the fail-fast hook script (to test interaction)
cat > .clarte/hooks/on-fail-fast.mjs << 'HOOKEOF'
#!/usr/bin/env node
// Generated by clarte - do not edit
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";

if (process.env.CLARTE_HOOKS_DISABLED) process.exit(0);

let input;
try { input = JSON.parse(readFileSync(0, "utf-8")); } catch { process.exit(0); }
const tool = input.tool_name;
if (!tool) process.exit(0);

const STATE_DIR = ".clarte/hooks/.state";
const STATE_FILE = STATE_DIR + "/fail-fast.json";
const THRESHOLD = 3;
const TEST_RE = /\b(npm\s+test|npm\s+run\s+test|pnpm\s+(run\s+)?test|yarn\s+test|bun\s+(run\s+)?test|npx\s+(vitest|jest|mocha)|vitest|jest|mocha|pytest|cargo\s+test|go\s+test)\b/;
const debug = process.env.CLARTE_HOOK_DEBUG === "1";

function log(msg) { if (debug) process.stderr.write("[fail-fast] " + msg + "\n"); }

function readState() {
  try { return JSON.parse(readFileSync(STATE_FILE, "utf-8")); } catch { return { base: "", count: 0 }; }
}

function writeState(state) {
  try { mkdirSync(STATE_DIR, { recursive: true }); writeFileSync(STATE_FILE, JSON.stringify(state)); } catch {}
}

function extractBase(cmd) {
  return cmd.split("|")[0].replace(/\s*2>&1\s*$/, "").trim();
}

if (tool !== "Bash" && tool !== "Edit" && tool !== "Write") process.exit(0);

if (existsSync(".clarte/fail-fast-override")) {
  log("override file found, skipping");
  process.exit(0);
}

if (tool === "Edit" || tool === "Write") {
  log("edit/write detected, resetting state");
  writeState({ base: "", count: 0 });
  process.exit(0);
}

if (tool === "Bash") {
  const cmd = input.tool_input?.command || "";
  if (TEST_RE.test(cmd)) {
    const base = extractBase(cmd);
    const state = readState();
    if (state.base === base) {
      state.count += 1;
    } else {
      state.base = base;
      state.count = 1;
    }
    log("test #" + state.count + " base: " + base.slice(0, 80));
    writeState(state);
    if (state.count >= THRESHOLD) {
      const output = JSON.stringify({
        hookSpecificOutput: {
          hookEventName: "PreToolUse",
          permissionDecision: "deny",
          permissionDecisionReason: "Blocked: you have run the same test command " + state.count + " times with no code edits in between. The test output will not change. Re-read the existing output and try a different fix, or create .clarte/fail-fast-override to disable this check."
        }
      });
      process.stdout.write(output);
      process.exit(0);
    }
  }
}
HOOKEOF

# Configure .claude/settings.json
cat > .claude/settings.json << 'SETTINGS'
{
  "hooks": {
    "PreToolUse": [
      {
        "hooks": [{ "type": "command", "command": "node .clarte/hooks/on-fail-fast.mjs" }]
      },
      {
        "hooks": [{ "type": "command", "command": "node .clarte/hooks/on-truncate-test.mjs" }]
      }
    ]
  }
}
SETTINGS

echo "[phase0] Hook configuration:"
cat .claude/settings.json

echo ""
echo "[phase0] Running claude -p 'run npm test and report results'..."
echo ""

# ── Run the session ────────────────────────────────────────────────
claude -p "Run 'npm test' and report what you see." \
  --output-format json \
  --model "${MODEL:-sonnet}" \
  --max-budget-usd "$MAX_BUDGET" \
  --allowedTools "$ALLOWED_TOOLS" \
  --dangerously-skip-permissions \
  > "$RESULTS_DIR/phase0.json" 2>"$RESULTS_DIR/phase0-stderr.txt" || true

echo "[phase0] Session complete."

# ── Collect session log ────────────────────────────────────────────
session_id=$(node --eval "try{const d=require('$RESULTS_DIR/phase0.json');if(d.session_id)console.log(d.session_id)}catch{}" 2>/dev/null)
if [ -n "$session_id" ]; then
  abs_work_dir=$(pwd)
  # Claude Code uses a leading dash instead of the first slash
  project_dir_name="-$(echo "$abs_work_dir" | sed 's|^/||; s|/|-|g')"
  log_src="$HOME/.claude/projects/${project_dir_name}/${session_id}.jsonl"
  if [ -f "$log_src" ]; then
    cp "$log_src" "$RESULTS_DIR/session.jsonl"
    echo "[phase0] Session log saved to $RESULTS_DIR/session.jsonl"
  else
    echo "[phase0] WARNING: Session log not found at $log_src"
  fi
else
  echo "[phase0] WARNING: Could not extract session_id"
fi

# ── Analyze results ───────────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  PHASE 0 ANALYSIS"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# Check 1: Did updatedInput rewrite the command?
if [ -f "$RESULTS_DIR/session.jsonl" ]; then
  echo "Check 1: updatedInput rewrite"
  # Look for the rewritten command in tool execution
  if grep -q "set -o pipefail" "$RESULTS_DIR/session.jsonl"; then
    echo "  PASS: Found 'set -o pipefail' in session log (command was rewritten)"
  else
    echo "  FAIL: No 'set -o pipefail' found (updatedInput may be ignored)"
  fi

  echo ""
  echo "Check 2: Output truncation"
  # Count how many of our padding lines appear in the tool response
  padding_count=$(grep -c "test output padding" "$RESULTS_DIR/session.jsonl" 2>/dev/null || echo "0")
  echo "  Padding lines in session: $padding_count (50 = no truncation, <20 = truncated)"

  echo ""
  echo "Check 3: Exit code preservation"
  # Look for non-zero exit code in tool response
  if grep -q '"exitCode":1\|"exit_code":1\|"exitCode": 1\|"exit_code": 1' "$RESULTS_DIR/session.jsonl"; then
    echo "  PASS: Non-zero exit code preserved"
  elif grep -q 'exit code' "$RESULTS_DIR/session.jsonl"; then
    echo "  INCONCLUSIVE: Found 'exit code' mention, inspect manually"
  else
    echo "  INCONCLUSIVE: Check session log manually"
  fi

  echo ""
  echo "Check 4: Hook debug log"
  if [ -f "$WORK_DIR/.clarte/hooks/truncate-debug.log" ]; then
    cat "$WORK_DIR/.clarte/hooks/truncate-debug.log"
  else
    echo "  No debug log (hook never fired)"
  fi

  echo ""
  echo "Check 5: Fail-fast counter"
  if [ -f "$WORK_DIR/.clarte/hooks/.state/fail-fast.json" ]; then
    echo "  State file: $(cat "$WORK_DIR/.clarte/hooks/.state/fail-fast.json")"
  else
    echo "  No state file (test may not have run, or was only run once)"
  fi
else
  echo "  No session log available. Check $RESULTS_DIR/phase0.json manually."
fi

echo ""
echo "Raw results: $RESULTS_DIR/"
echo "Session log: $RESULTS_DIR/session.jsonl"
echo ""
echo "Manual inspection:"
echo "  grep 'pipefail' $RESULTS_DIR/session.jsonl"
echo "  grep 'tail -20' $RESULTS_DIR/session.jsonl"
echo "  grep 'padding' $RESULTS_DIR/session.jsonl"
